### ISSUE TITLE
Set skip install build setting for iOS static libraries

### ISSUE THREAD

**Issue by izackp** [microsoft/plcrashreporter#102]
It's currently set to 'no' which interferes with archiving and deploying on iOS. 

Instead of creating a proper archive you can upload to TestFlight it creates an archive of two products: the app, and the static library + headers which is incompatible.

**Comment by Jamminroot** [comment]
Thanks for reporting that. I'll investigate it a bit later today, and open a PR if it everything's fine.

**Comment by MatkovIvan** [comment]
Hey!
We've included the fix for this issue to the latest SDK release ([1.7.1](https://github.com/microsoft/plcrashreporter/releases/tag/1.7.1)).
I'm closing it, but please reopen if you some questions or run into this again.
