### ISSUE TITLE
Duplicate symbols in applications with -all_load flag

### ISSUE THREAD

**Issue by jstoffer** [microsoft/plcrashreporter#105]
duplicate symbol '_PLCrashReporterException' in:
    Pods/PLCrashReporter/iOS Framework/CrashReporter.framework/CrashReporter(CrashReporter-x86_64-master.o)
    Pods/PLCrashReporter/iOS Framework/CrashReporter.framework/CrashReporter(CrashReporter.o)
 duplicate symbol '_PLCrashReporterErrorDomain' in:
     Pods/PLCrashReporter/iOS Framework/CrashReporter.framework/CrashReporter(CrashReporter-x86_64-master.o)
     Pods/PLCrashReporter/iOS Framework/CrashReporter.framework/CrashReporter(CrashReporter.o)
 ld: 2 duplicate symbols for architecture x86_64

**Comment by jstoffer** [comment]
work-around seems to be switching from CocoaPods to Swift Package Manager

**Comment by MatkovIvan** [comment]
Hi @jstoffer,

Thanks for getting in touch!
I've double checked this and confirm that the binaries really contain these symbols twice. However, it works fine with CocoaPods in all our test applications.
After some investigation I've figure out why all out test apps works fine with this binary - it doesn't set `-all_load` flag. This problem affects only iOS and tvOS `.framework`s. Static libraries (`.a`) for these platforms and macOS binaries are valid.

Anyway, this is a bug, so I'm adding appropriate label. I'll take care about this issue and add this case to our tests.

**Comment by sevaa** [comment]
Same error on ARM64:

>duplicate symbol '_PLCrashReporterException' in:
>    ../Libs/CrashReporter.framework/CrashReporter(CrashReporter-arm64-master.o)
>    ../Libs/CrashReporter.framework/CrashReporter(CrashReporter.o)
>duplicate symbol '_PLCrashReporterErrorDomain' in:
>    ../Libs/CrashReporter.framework/CrashReporter(CrashReporter-arm64-master.o)
>    ../Libs/CrashReporter.framework/CrashReporter(CrashReporter.o)
>ld: 2 duplicate symbols for architecture arm64

**Comment by MatkovIvan** [comment]
@sevaa yes, version 1.7.0 and architectures aside of `x86_64` have the same issue. For these versions I can only suggest avoid using `-all_load` flag or use static library instead of framework.
I've already prepared the PR with fix (#106), so it will be fixed with the next patch.

**Comment by MatkovIvan** [comment]
Hey!
We've included the fix for this issue to the latest SDK release ([1.7.1](https://github.com/microsoft/plcrashreporter/releases/tag/1.7.1)).
I'm closing it, but please reopen if you some questions or run into this again.
