### ISSUE TITLE
Can I post crash log to Server on app Crash? I want post app's crash log to server while app crashing instead of  launching app again?

### ISSUE THREAD

**Issue by tanpengsccd** [microsoft/plcrashreporter#120]
### **Description**
Can I post crash log to Server on app Crash? I want post app's crash log to server while app crashing instead of  launching app again?

### **Repro Steps**
```
 func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        let config = PLCrashReporterConfig.init(signalHandlerType: .BSD, symbolicationStrategy: .all, shouldRegisterUncaughtExceptionHandler: true)
        let reporter = PLCrashReporter.init(configuration: config)
        var cb:PLCrashReporterCallbacks = .init(version: 0,
                                                context: UnsafeMutableRawPointer.init(bitPattern: 0xABABABAB),
                                                handleSignal:  { (info,  uap, context) in
                                                    print("enter call back!!!")
                                                    print(info?.pointee,uap?.pointee,context)
                                                   
                                                     try? reporter?.loadPendingCrashReportDataAndReturnError()//Here I can't get reporter: "A C function pointer cannot be formed from a closure that captures context"
                                                    
                                                    
                                                })
        
        
        
        
        reporter?.setCrash(&cb)
        do {
            try  reporter?.enableAndReturnError()
        } catch let error {
            
            print("failed:",error)
        }
       
        return true
    }
```

### **Details**

1. Which SDK version are you using?
1.7.1
2. Which OS version did you experience the issue on?
iOS 14.0 beta
3. Which CocoaPods/Carthage/Xcode version are you using?
12.beta.3
4. What device version did you see this error on? Were you using an emulator or a physical device?
iPhone 6s
5. What language are you using?
    - [ X] Objective C
    - [ O] Swift
6. What third party libraries are you using?
PODS:
  - Alamofire (5.2.2)
  - netfox (1.19.0)
  - PLCrashReporter (1.7.1)

**Comment by MatkovIvan** [comment]
No, it can't be implemented. The callback has much stricter restrictions, not to mention network calls.
You can read more about it in the docs for this:
https://github.com/microsoft/plcrashreporter/blob/5e013e00ad342d8ccaae767fef5a1ef117514ce8/Source/CrashReporter.h#L205-L231
