### ISSUE TITLE
How to conditionally enable/disable PLCrashreporter?

### ISSUE THREAD

**Issue by PravinPushkar** [microsoft/plcrashreporter#122]
Hi,

I am trying out PLCrashreporter in one of my app. I want to control the crash collection based on the user's server configuration.

Suppose the user has some server flag say ENABLE_CRASH_COLLECTION.
If this flag is set to false, I want to disable/stop the PLCrashreporter from collecting crashes in runtime.

Currently, I am fetching the server flag value, but I could not find any api to stop the crashreporter, while app is in running state.

Any help or pointer would really be helpful. I am using latest release build of PLCrashreporter

Thanks,
Pravin

**Comment by MatkovIvan** [comment]
Hey @PravinPushkar 👋 

PLCrashReporter does not support disabling at runtime - crash handlers on Apple platforms is not a thing that can be easily switched at runtime.
The best strategy is to stop processing/delete already collected reports and do to initialize PLCrashReporter on next run. We're using this strategy in [App Center](https://appcenter.ms/) (that uses PLCrashReporter under the hood).

Closing this, but feel free to reply/reopen if you have more questions.

**Comment by PravinPushkar** [comment]
> Hey @PravinPushkar 👋
> 
> PLCrashReporter does not support disabling at runtime - crash handlers on Apple platforms is not a thing that can be easily switched at runtime.
> The best strategy is to stop processing/delete already collected reports and do to initialize PLCrashReporter on next run. We're using this strategy in [App Center](https://appcenter.ms/) (that uses PLCrashReporter under the hood).
> 
> Closing this, but feel free to reply/reopen if you have more questions.

Hi MatkovIvan,

Sorry, re-opening it for some clarification regarding your last input.

You mean to say that, If the server config comes out to be "false(meaning do not collect crashes)", then I should basically restart the app and this time I should not initialise the PLCrashreporter ?.

**Comment by MatkovIvan** [comment]
In general - yes. The main idea is to do not send the crash reports with this flag, right? So, if this flag is set, just do not start SDK anymore (next launch) and delete already collected reports. Forcing to restart the app is up to you of course, but it doesn't sound required to avoid sending (not collecting) reports - if the session where you received this flag crashes - you can just do not process/purge the report next time.
