### ISSUE TITLE
Issues when trying to use in iOS with Cocoapods in a dynamic framework

### ISSUE THREAD

**Issue by nachoBonafonte** [microsoft/plcrashreporter#128]
**Is your feature request related to a problem? Please describe.**
I would like to use `PLCrashReporter` as a dependency of another dynamic library say `A` when using Cocoapods in iOS. But as the `PLCrashReporter` framework is distributed as a vendored static framework, it forces to make `A` framework static or fails when running `pod install` in the app that references framework `A`. Fails with a message like: `target has transitive dependencies that include statically linked binaries`

**Describe the solution you'd like**
I would like to have a way to use PLCrashReporter with Cocoapods with iOS or tvOS  as a dynamic framework (as macOS version is doing)

**Describe alternatives you've considered**
Don't know if that can be done using a subspec and a different vendored build, or a different podspec is needed for that.

**Comment by olmisa** [comment]
Hey, @nachoBonafonte , thanks for bringing this to our sight. 
We're going to discuss it with our team, and see if there's anything we can do at this point.

**Comment by nachoBonafonte** [comment]
Hi @olmisa, any news on this front? Thanks a lot

**Comment by MatkovIvan** [comment]
@nachoBonafonte sorry to say, but we have no plans to release dynamic framework for iOS yet.

Also, the error message makes sense: if the library is already linked to the dynamic framework binary, it should not be a transitive dependency.
Possible workaround here is to include PLCrashReporter via not CocoaPods.

Related thread: https://github.com/microsoft/appcenter-sdk-apple/issues/1227
