### ISSUE TITLE
Timestamp value is nil in SystemInfo

### ISSUE THREAD

**Issue by PravinPushkar** [microsoft/plcrashreporter#129]
Hi,

I am using PLCrashreporter in my project. I want to fetch the timestamp when the report was generated by using report.systemInfo.timestamp, but this comes as nil. 
It is written in the document that it may be nil if the date is unavailable. 
Any help would be helpful in figuring out the reason for it to be coming as nil and what workaround is recommended to resolve it.

Platform - IOS Simulator

**Comment by annakocheshkova** [comment]
Hi there! This value is collected via C++ [`time()`](http://www.cplusplus.com/reference/ctime/time/) method. 
[Here are some of the reasons](https://stackoverflow.com/a/49062241/7453375) this value can be null (or -1, under the hood).
What kind of simulator do you use (iOS version, etc)?
Is there a chance the time is incorrect there?

As a workaround, I can suggest checking for this value at the moment of loading the crash and adding a fallback:
```
NSData *data = [reporter loadPendingCrashReportDataAndReturnError: &error];
PLCrashReport *report = [[PLCrashReport alloc] initWithData: data error: &error];
if (report.systemInfo.timestamp == nil) { ... }
```

**Comment by annakocheshkova** [comment]
Hey! Have you got any more questions? If so, please let us know. 
For now I'm going to close this issue.
