### ISSUE TITLE
Xcode 12 SPM `IPHONEOS_DEPLOYMENT_TARGET` warning

### ISSUE THREAD

**Issue by diogot** [microsoft/plcrashreporter#130]
### **Description**

When using Xcode 12 GM there is a warning:

> The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.

### **Repro Steps**

1. Download Xcode 12
2. Add as a SPM dependency
3. Build

### **Details**

1. Which SDK version are you using? 
 Xcode Version 12.0 (12A7208)

2. Which OS version did you experience the issue on?
  iOS 14

3. Which CocoaPods/Carthage/Xcode version are you using?
  Xcode Version 12.0 (12A7208) with SPM
  
4. What device version did you see this error on? Were you using an emulator or a physical device?
 Xcode

5. What language are you using?
    - [ ] Objective C
    - [X] Swift

6. What third party libraries are you using?
  AppCenter

According to [this thread](https://forums.swift.org/t/minimum-ios-version-xcode-12-and-build-warnings/40224/3) the problem is that  [this](https://github.com/microsoft/plcrashreporter/blob/af3a0a1248adc690354de07e5e36e8bcc7314e72/Package.swift#L8) line is overriding Xcode settings forcing `IPHONEOS_DEPLOYMENT_TARGET` to an unsupported SDK version by Xcode 12.

The solution on the thread was remove the `platforms` section, because they support all platforms/versions so this might not work in this case.

**Comment by MatkovIvan** [comment]
Hi there.

It's kind of expected because PLCrashReporter still supports iOS 8 devices. Since it's just a warning, you can ignore it for now.
I'm going to keep this issue open as the request of dropping iOS 8 support.

**Comment by diogot** [comment]
Thanks!

**Comment by nostradani** [comment]
The reason here is that Swift 5.3 does not support iOS 8 anymore and therefore Xcode 12 (using Swift 5.3) will print this warning. 

@MatkovIvan you can resolve that warning AND keep iOS 8 compatibility by checking the toolchain version in the Package.swift file. This here should work:

`#if swift(>=5.3)
let ios = SupportedPlatform.iOS(.v8)
#else
let ios = SupportedPlatform.iOS(.v9)
#endif

let package = Package(
    name: "PLCrashReporter",
    platforms: [
        ios,
        .macOS(.v10_10),
        .tvOS(.v9)
    ],
    products: [
        .library(name: "CrashReporter", targets: ["CrashReporter"])
    ],
    targets: [
        .target(
            name: "CrashReporter",
            path: "",
            exclude: [
                "Source/dwarf_opstream.hpp",
                "Source/dwarf_stack.hpp",
                "Source/PLCrashAsyncDwarfCFAState.hpp",
                "Source/PLCrashAsyncDwarfCIE.hpp",
                "Source/PLCrashAsyncDwarfEncoding.hpp",
                "Source/PLCrashAsyncDwarfExpression.hpp",
                "Source/PLCrashAsyncDwarfFDE.hpp",
                "Source/PLCrashAsyncDwarfPrimitives.hpp",
                "Source/PLCrashAsyncLinkedList.hpp",
                "Source/PLCrashReport.proto"
            ],
            sources: [
                "Source",
                "Dependencies/protobuf-c"
            ],
            cSettings: [
                .define("PLCR_PRIVATE"),
                .define("PLCF_RELEASE_BUILD"),
                .define("PLCRASHREPORTER_PREFIX", to: ""),
                .define("SWIFT_PACKAGE"), // Should be defined by default, Xcode 11.1 workaround.
                .headerSearchPath("Dependencies/protobuf-c")
            ],
            linkerSettings: [
                .linkedFramework("Foundation")
            ]
        )
    ]
)`

**Comment by MatkovIvan** [comment]
@nostradani thanks for suggestion. However, it's not only about SwiftPM.

**Comment by nostradani** [comment]
Yes, I noticed that the Xcode project has the same issue when you open it with Xcode 12.
However the Xcode project AFAIK does not allow any kind of dynamic values for the deployment target based on the used Xcode version.

Still that doesn't mean, that you shouldn't resolve the issue for SPM. At least people using SPM would have a valid fix (not only a workaround). I create a pull request for it: 
https://github.com/microsoft/plcrashreporter/pull/140

**Comment by MatkovIvan** [comment]
The fix has been merged
