### ISSUE TITLE
Bulid failure on Xcode 12 GM 

### ISSUE THREAD

**Issue by taehoon-jung** [microsoft/plcrashreporter#131]
### **Description**

I can't build for iOS on Xcode12 GM.

### **Repro Steps**

Please list the steps used to reproduce your issue.

##### 1. Xcode 12 with v1.7.2
1. Download Xcode 12 GM
2. Checkout v1.7.2
3. Choose target CrashReporter iOS Framework / CrashReporter iOS Universal
     - both are failed

##### 2. Xcode 12 with master branch
1. Download Xcode 12 GM
2. Checkout master (#af3a0a1248adc690354de07e5e36e8bcc7314e72)
3. Choose target CrashReporter iOS Framework or CrashReporter iOS Universal 
     - CrashReporter iOS Framework succeed
     - CrashReporter iOS Universal failed
3.1 If I add .xcconfig on project, then both builds are succeed. but carthage was still failed.
```
EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64=arm64 arm64e armv7 armv7s armv6 armv8
EXCLUDED_ARCHS=$(inherited) $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT))
```

##### 3. Carthage
1. Add dependency on Cartfile
   - `github "https://github.com/microsoft/plcrashreporter"			>= 1.7.1`
2. carthage update --platform ios 
- (failed)

##### 4. Carthage with .xcconfig
- I found a workaround related with carthage on xcode 12
   - https://github.com/Carthage/Carthage/issues/3019
- other projects are works well with upper workaround but plccrashreporer doesn't working.

### **Details**

1. Which SDK version are you using? 
XCode 12.0 (12A7208)

2. Which OS version did you experience the issue on? 
iOS 14

3. Which CocoaPods/Carthage/Xcode version are you using?
Carhage / XCode

4. What device version did you see this error on? Were you using an emulator or a physical device?
- XCode
```
Showing All Messages
fatal error: lipo: /$USER_HOME/Library/Developer/Xcode/DerivedData/CrashReporter-dvugesngrmqtvbcdmayplbtumulb/Build/Products/Debug-iphoneos/libCrashReporter.a and /$USER_HOME/Library/Developer/Xcode/DerivedData/CrashReporter-dvugesngrmqtvbcdmayplbtumulb/Build/Products/Debug-iphonesimulator/libCrashReporter.a have the same architectures (arm64) and can't be in the same fat output file
```
- Carthage
```

MasterObjectLink /$USER_HOME/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7208/plcrashreporter/d743a2e8805790ca8abfda7200de04f72c99171b/Build/Intermediates.noindex/CrashReporter.build/Release-iphonesimulator/CrashReporter\ iOS\ Framework.build/Objects-normal/CrashReporter-i386-master.o (in target 'CrashReporter iOS Framework' from project 'CrashReporter')
    cd /$USER_HOME/$PROJECT_HOME/Carthage/Checkouts/plcrashreporter
    /Applications/Xcode_12_GM.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld -r -arch i386 -syslibroot /Applications/Xcode_12_GM.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk /$USER_HOME/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7208/plcrashreporter/d743a2e8805790ca8abfda7200de04f72c99171b/Build/Intermediates.noindex/CrashReporter.build/Release-iphonesimulator/CrashReporter\ iOS\ Framework.build/Objects-normal/i386/CrashReporterFramework.o /$USER_HOME/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7208/plcrashreporter/d743a2e8805790ca8abfda7200de04f72c99171b/Build/Products/Release-iphonesimulator/libCrashReporter.a -o /$USER_HOME/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7208/plcrashreporter/d743a2e8805790ca8abfda7200de04f72c99171b/Build/Intermediates.noindex/CrashReporter.build/Release-iphonesimulator/CrashReporter\ iOS\ Framework.build/Objects-normal/CrashReporter-i386-master.o
ld: file not found: /$USER_HOME/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7208/plcrashreporter/d743a2e8805790ca8abfda7200de04f72c99171b/Build/Products/Release-iphonesimulator/libCrashReporter.a
Command MasterObjectLink failed with a nonzero exit code

** BUILD FAILED **


The following build commands failed:
	MasterObjectLink /$USER_HOME/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7208/plcrashreporter/d743a2e8805790ca8abfda7200de04f72c99171b/Build/Intermediates.noindex/CrashReporter.build/Release-iphonesimulator/CrashReporter\ iOS\ Framework.build/Objects-normal/CrashReporter-i386-master.o
(1 failure)
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /$USER_HOME/$PROKJECT_HOME/Carthage/Checkouts/plcrashreporter/CrashReporter.xcodeproj -scheme CrashReporter\ iOS\ Framework -configuration Release -derivedDataPath /$USER_HOME/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7208/plcrashreporter/d743a2e8805790ca8abfda7200de04f72c99171b -sdk iphonesimulator -destination platform=iOS\ Simulator,id=E62E1B2B-79BA-4D80-902B-3A0A97AA2DF3 -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /$USER_HOME/$PROJECT_HOME/Carthage/Checkouts/plcrashreporter)
```

5. What language are you using?
    - [O] Objective C
    - [O] Swift

6. What third party libraries are you using?
- NO
- I tested standalone or simple project

**Comment by MatkovIvan** [comment]
Hi @taehoon-jung,

Thanks for getting in touch! We verified it on the beta recently and it worked 🤔 
The problem here is clearly that simulator now has `arm64` arch, so the old "fat" universal libs can't be built because of duplicates. We'll look at it, thanks.

**Comment by MatkovIvan** [comment]
@taehoon-jung are you trying to build it on ARM mac?

**Comment by taehoon-jung** [comment]
@taehoon-jung  no i am doing it on Intel mac.

**Comment by MatkovIvan** [comment]
Hi @taehoon-jung,
Please check out my fix from #132, this should fix this problem

**Comment by taehoon-jung** [comment]
Hi, @MatkovIvan 
Sorry for late reply.
I tested the branch yesterday, the project got succeed from building but It didn't still work when I use carthage. 
Following the error log, It coundn't find `libCrashReporter.a` 

```
ld: file not found: /$USER_HOME/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7208/plcrashreporter/1a56a889ede0a0f8d82c3ada8d03af884832880b/Build/Products/Release-iphonesimulator/libCrashReporter.a
Command MasterObjectLink failed with a nonzero exit code
```

Cound you check it? 

Thank you

**Comment by MatkovIvan** [comment]
@taehoon-jung This one is more interesting. Xcode 12 tries to use `libCrashReporter.a` before creating it, despite speccified target dependencies:

```
...
▸ Compiling PLCrashAsyncCompactUnwindEncoding.c
▸ Compiling PLCrashAsync.c
▸ Compiling CrashReporter.m
▸ Compiling CrashReporterFramework.m
▸ Compiling CrashReporterFramework.m

❌  ld: file not found: /$USER_HOME/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/plcrashreporter/7de33819a0a48e6fc19f28c0808baca4561d50d6/Build/Products/Release-iphonesimulator/libCrashReporter.a



❌  ld: file not found: /$USER_HOME/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/plcrashreporter/7de33819a0a48e6fc19f28c0808baca4561d50d6/Build/Products/Release-iphonesimulator/libCrashReporter.a


▸ Building library libCrashReporter.a
▸ Processing Info.plist
▸ Touching CrashReporter.framework (in target 'CrashReporter iOS Framework' from project 'CrashReporter')
** BUILD FAILED **
```

It's not related to Carthage, I'm able to repro it from Xcode command line and Xcode UI. It's clearly Xcode 12 bug 😞 
I've opened #136 with disabling parallel build to work around this problem.

**Comment by taehoon-jung** [comment]
@MatkovIvan Thank you! 
I checked your PR (https://github.com/microsoft/plcrashreporter/pull/136).
Could you share schedule of next version release?
Thank you again.

**Comment by MatkovIvan** [comment]
no exact ETA yet. But since you're using source distribution (not pre-built binaries), it should be a big problem, right?

**Comment by taehoon-jung** [comment]
@MatkovIvan yes.. we can't upgrade our dev environment. We need to upgrade it to solve ios14 issues as soon as possible.
