### ISSUE TITLE
CPU architecture is detected as "arm64-unknown" on iOS 14

### ISSUE THREAD

**Issue by Jack-Rain** [microsoft/plcrashreporter#133]
when run in iOS 14， it get “arm64-unknown”

**Comment by Jamminroot** [comment]
Hello, we appreciate your efforts bringing this to our attention, but without proper description, we wouldn't be able to troubleshoot the issue. 
Can you elaborate on how, and where do you get this message? How exactly you "run"? Preferrable, use a [template](https://github.com/microsoft/plcrashreporter/blob/master/.github/ISSUE_TEMPLATE/problem_report.md)

**Comment by Jack-Rain** [comment]
![image](https://user-images.githubusercontent.com/14190589/94135267-d0823d80-fe95-11ea-8d49-803da71c1798.png)
when running our app on iOS14，the archName is ”arm64-unknown“ in the crash log。

**Comment by a20251313** [comment]
it occurs on machine  that cpu is arm64e, Such as XS Max

**Comment by Jamminroot** [comment]
We'll have a look at this problem and update you upon result in this thread.

**Comment by krassx** [comment]
AFAICT, this is due to the flags set on the subtype field and which should be filtered out with CPU_SUBTYPE_MASK (defined in the Mach-O headers). In the particular case described about, that should look like:

```
imageInfo.codeType.subtype & ~CPU_SUBTYPE_MASK;
```

whereas the mask itself is defined as

```
#define CPU_SUBTYPE_MASK 0xff000000;
```

**Comment by MatkovIvan** [comment]
The fix merged

**Comment by damirdavletov** [comment]
> The fix merged

@MatkovIvan thanks for having the fix merged! Are you planning a release with this fix anytime soon?

**Comment by MatkovIvan** [comment]
some kind of, but no exact ETA
