### ISSUE TITLE
Add via SPM

### ISSUE THREAD

**Issue by bruno-garcia** [microsoft/plcrashreporter#145]
### **Description**

I'm trying to add the library via SPM but failing to do so.

### **Repro Steps**

I have a repro where I:

1. Created a new project with a plain `swift package init --type=executable ([here](https://github.com/bruno-garcia/plcrashreporter-spm-repro/commit/73b48ab74c49716c9c2b0f199e953f550944a600))
2. Tried to add the library [here](https://github.com/bruno-garcia/plcrashreporter-spm-repro/commit/cd291c1caddf1ce258b25e50b0927f35f4495293)

Errors as:

```
'plcrashreporter-spm-repro' /Users/bruno/temp/plcrashreporter-spm-repro: error: product 'PLCrashReporter' not found. It is required by target 'plcrashreporter-spm-repro'.
warning: dependency 'PLCrashReporter' is not used by any target
```

### **Details**

```
macOS 10.15.7

Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)
Target: x86_64-apple-darwin19.6.0
```

Am I adding this wrong?

**Comment by olmisa** [comment]
Hi @bruno-garcia ,
thanks for using PLCrashReporter.
There is one mistake in target dependency (wrong dependency product name). I created [PR](https://github.com/bruno-garcia/plcrashreporter-spm-repro/pull/1/files) with a right target dependency. Now it should work.
Thanks

**Comment by bruno-garcia** [comment]
That indeed solves the problem! thank you very much.
One suggestion: Add a line on "how to install with Swift Package Manager" to the readme.

Happy to open a PR if you'd like
