### ISSUE TITLE
App will not crash back while catching the crash of swift / C++ but stuck on current interface

### ISSUE THREAD

**Issue by ZP-L-Daniel** [microsoft/plcrashreporter#147]
### **Description**

I use PLCrashReporter in a swift project with some C++ code. when catching a crash of Swift or C++, App will not crash back but stuck on current interface. Even if I kill the App process and restart it, the App still stays on the current interface.

### **Details**

1. The SDK version is 1.7.2
2. The OS version is iOS12.4.8

**Comment by MatkovIvan** [comment]
How do you initialize the library? What signal handler type and symbolication strategy do you use?

**Comment by ZP-L-Daniel** [comment]
> Hi! Thanks for getting in touch with us!
> I try to reproduce this issue, but for me, it works right. Could you please clarify how you crash your app and what the type of error you call? Also could you please clarify is it happen on the simulator too? Or only on the device?

The Swift error type is index out of range. I try to access **A[10]** while **A** is a array with 1 element. And i call this in tableView(_:didSelectRowAt:) method.
The C++ error type is EXC_BAD_ACCESS. I try to access a wild pointer.
This issue happens on the simulator too.

**Comment by ZP-L-Daniel** [comment]
> How do you initialize the library? What signal handler type and symbolication strategy do you use?

Here is the initialization code：
`@try 
{
    PLCrashReporterConfig* config = [[PLCrashReporterConfig alloc]
                                                               initWithSignalHandlerType:PLCrashReporterSignalHandlerTypeBSD 
                                                                      symbolicationStrategy:PLCrashReporterSymbolicationStrategyNone
                                    shouldRegisterUncaughtExceptionHandler:YES];
     self.crashReporter = [[PLCrashReporter alloc] initWithConfiguration:config];
     [self.crashReporter enableCrashReporter];
}`

**Comment by AnastasiaKubova** [comment]
Thanks for share additional info! I try to reproduce it follow your steps, but it still works right for me.
Have you a chance to share the sample project with reproducing this. It will be helpful in investigating your issue.

**Comment by AnastasiaKubova** [comment]
We haven’t heard from you in a while so I’m closing this issue.
Feel free to reopen this issue if it isn’t resolved or you have additional questions.
