### ISSUE TITLE
SIGSEGV / SEGV_MAPERR when calling -generateLiveReport

### ISSUE THREAD

**Issue by jakob** [microsoft/plcrashreporter#154]
I sometimes get a crash when calling `[PLCrashReporter generateLiveReport]`

The crash seems to happen in this line:
https://github.com/microsoft/plcrashreporter/blob/de6b8f9db4b2a0aa859a5507550a70548e4da936/Source/PLCrashAsyncObjCSection.mm#L776

I tried debugging, and it looks like `cursor` points to unmapped memory.

I'm on macOS 10.15.7, my app is built using XCode 12.2, and I'm using PLCrashReporter 1.8.1

The crash doesn't always happen. I'm trying to find a minimal test case. I'll follow up on this issue once I know more.

**Comment by jakob** [comment]
I've tried different releases of PLCrashReporter. I've been able to reproduce the crash with 1.8.1 and 1.8.0

I have not been able to reproduce the issue with release 1.7.2

**Comment by MatkovIvan** [comment]
Hi @jakob,

Thanks for getting in touch!

> I'm trying to find a minimal test case.

It would be great.

> I have not been able to reproduce the issue with release 1.7.2

I do not see any related changes in 1.8.0, waiting more info/reproduction steps for now.

Also, I want to note that this line is part of local symbolycation that is highly recommended to be disabled in release builds, see
https://github.com/microsoft/plcrashreporter/blob/de6b8f9db4b2a0aa859a5507550a70548e4da936/Source/PLCrashReporterConfig.h#L102-L117

**Comment by jakob** [comment]
Thanks for getting back to me! I think I found the problem.

Apparently the method list is not in the `__objc_const` section, so it tries to look in the `__objc_const_ax` section, but it doesn't check if `objcConstAxMobj` is initialized, so if there is no `__objc_const_ax` section it reads uninitialized data.

The problem is in this line:
https://github.com/microsoft/plcrashreporter/blob/de6b8f9db4b2a0aa859a5507550a70548e4da936/Source/PLCrashAsyncObjCSection.mm#L743

I'll open a PR.

While debugging this code, I've started to wonder why this code is so complicated, and why it doesn't just access the memory directly. Is the idea to make the code more robust when memory is corrupted? Or to make it async safe? Or to support generating crash reports for other processes?

Also, if I disable local symbolication, how would I go about getting symbols for Apple frameworks? I keep archives for all releases of my app, but I don't have symbols for all of Apple's frameworks.

**Comment by MatkovIvan** [comment]
> I'll open a PR.

Thanks for that!

> why this code is so complicated, and why it doesn't just access the memory directly. Is the idea to make the code more robust when memory is corrupted? Or to make it async safe? Or to support generating crash reports for other processes?

Your guesses are correct, there are a lot of checks if the memory is really readable. In addition, byte order needs to be converted in some cases.

> Also, if I disable local symbolication, how would I go about getting symbols for Apple frameworks?

There is a good [doc](https://developer.apple.com/documentation/xcode/diagnosing_issues_using_crash_reports_and_device_logs/adding_identifiable_symbol_names_to_a_crash_report) about it. In any case, server side symbolycation is the most robust one - for example the previous issue in this repo (#153) was exactly about it.

> but I don't have symbols for all versions of Apple's frameworks.

I'd suggest you use App Center (uses PLCR under the hood), where our team takes care of system symbols (and many other things) that makes it easier for you 😄

**Comment by jakob** [comment]
Thanks for pointing me to Apples docs, I haven't seen that one yet. I didn't know that Spotlight can look for DWARF files by UUID, that's a neat trick.

Unfortunately it confirms that I need copies of every version of macOS that my customers are using. I guess I'll stick with local symbolication. Worst case I don't get a crash report. I know that App Center exists, but I like our homemade crash reporting solution :)

Anyway, thanks a lot for getting back to me, and thanks a lot for taking care of PLCrashReporter. It seems it's in good hands again!
