### ISSUE TITLE
Support for more machine info.

### ISSUE THREAD

**Issue by egorafanasenko** [microsoft/plcrashreporter#156]
**Is your feature request related to a problem? Please describe.**

Right now **plcrashreporter** only has couple field from NSException->userInfo->system_info. Is that possible to include all of them? (like _ios_jailbroken_, _device_battery_level_, _ram_available_)

**Describe the solution you'd like**

We would love to have all machine info from NSException.

**Describe alternatives you've considered**

Maybe there could be a way to customise what we parse from NSException.

**Additional context**
Add any other context about the feature request here.

**Comment by MatkovIvan** [comment]
Hi @egorafanasenko,

Thanks for getting in touch!

> all of them

It's a quite undefined description. So, replying just about your examples

> ios_jailbroken, device_battery_level, ram_available

I guess custom data + crash callback is the what you are looking for.

See 
https://github.com/microsoft/plcrashreporter/blob/de6b8f9db4b2a0aa859a5507550a70548e4da936/Source/PLCrashReporter.h#L137
You can put there any data that makes sense for you - ios_jailbroken in this case.

regarding device_battery_level and ram_available - you can try to use `setCrashCallbacks`, but please note that there are a lot of restrictions there, for example - you cannot safely call any Objective-C API. See
https://github.com/microsoft/plcrashreporter/blob/de6b8f9db4b2a0aa859a5507550a70548e4da936/Source/CrashReporter.h#L205-L231

Also,
- "ios_jailbroken" - is clearly "custom" information.
- "device_battery_level" - API for that is Objective-C and cannot be safely call _after_ the crash (see comment above)
- "ram_available" - this one is probably makes sense to grab, but I'd say that custom data is the best choice for it now.

**Comment by MatkovIvan** [comment]
Hi, we haven't heard from you in a while and it can be handled by custom data so I'm closing this issue. Please reopen/comment if you have more questions.
