### ISSUE TITLE
Can this Crash framework coexist with other third-party Crash frameworks? Examples include Bugly and Umeng

### ISSUE THREAD

**Issue by tenxun123** [microsoft/plcrashreporter#158]
1. Which SDK version are you using?
  1.8.1
2. Which OS version did you experience the issue on?
Can this Crash framework coexist with other third-party Crash frameworks? Examples include Bugly and Umeng
3. Which CocoaPods/Carthage/Xcode version are you using?
4. What device version did you see this error on? Were you using an emulator or a physical device?
5. What language are you using?
    - [ ] Objective C
6. What third party libraries are you using?
bugly and Umeng framework

**Comment by olmisa** [comment]
Hello @tenxun123 ,
thanks for using PLCrashReporter. This framework can't coexist with other third-party Crash frameworks.
Thanks

**Comment by tenxun123** [comment]
Hello，olmisa
If I need to use other third-party frameworks at the same time, what do I need to change?

**Comment by olmisa** [comment]
Hello @tenxun123 ,
PLCrashReporter doesn't work correctly with other Crash frameworks in parallel. We don't provide support for this scenario.
Thanks

**Comment by lumaxis** [comment]
Just a small note to expand on what @olmisa said, @tenxun123: iOS does only allow you to add one third-party crash reporter. This is a system limitation that PLCrashReporter can do nothing about, even if we wanted to.

**Comment by tenxun123** [comment]
@olmisa IOS is compatible with multiple crash collections。
       UncaughtException if at the same time have many registration by NSSetUncaughtExceptionHandler exception handler, peace is: after the registration by NSGetUncaughtExceptionHandler remove others previously registered handler and backup, in your own handler after processing consciously put others handler registered back, don't pass。

**Comment by AnastasiaKubova** [comment]
On iOS not possible to use more than one third-party crash reporting tool at a time. If you will use several libraries for crash reporting in actually only one of them will be catch and report crash reports correctly.

**Comment by AnastasiaKubova** [comment]
We haven’t heard from you in a while so I’m closing this issue.
Feel free to reopen this issue if it isn’t resolved or you have additional questions.

**Comment by MatkovIvan** [comment]
@tenxun123 I just wanted to note that iOS crash handling is way more complicated than using `NSSetUncaughtExceptionHandler` where you can save previous one to chain the handlers. You can find more highlights what is happening under the hood in [this file](https://github.com/microsoft/plcrashreporter/blob/1.8.1/Source/CrashReporter.h) or generated docs (it can be found in the release archive) based on these comments (mach exception server, signal handlers, etc) The answers above are correct - it cannot work with other crash handlers.
