### ISSUE TITLE
PLCrashReporter maintainership moving to Microsoft 

### ISSUE THREAD

**Issue by lumaxis** [microsoft/plcrashreporter#16]
Hi everyone!

I'm very pleased to let everyone know that [my team at Microsoft](https://appcenter.ms) has worked with @chrispcampbell and Plausible Labs and agreed to transfer this repo to the [`microsoft`](https://github.com/microsoft) organization on GitHub and we are taking over maintainership of the project going forward. More details will follow in blogposts that we're going to publish some time later today and that I'll of course add here, too. 😊

Having worked with PLCrashReporter ever since I started at [HockeyApp](https://www.hockeyapp.net/) in 2014, I'm really super happy that we found a way to keep this project healthy and am super looking forward to what's to come 🎉

If you have any questions, please feel free to ask them here, @derpixeldan and I are happy to answer.

**Comment by lumaxis** [comment]
And the repo transfer just happened! 📦

**Comment by sevaa** [comment]
I see there's a release/plcrashreporter-1.3 branch. Where's the download page for that release, please? The one at https://plcrashreporter.org/ offers 5 year old 1.2 as the stable release.

**Comment by MatkovIvan** [comment]
@sevaa 1.3 was never properly released

Also, see #23 for more information on the current state of the repo

**Comment by sevaa** [comment]
Understood, thanks. So when it's finally out, where *will* it be?

**Comment by lumaxis** [comment]
@sevaa Just following up here: We recently released version 1.4 which can be found here https://github.com/microsoft/plcrashreporter/releases/tag/1.4.0

**Comment by MrTact** [comment]
Is there a new home for documentation? The site (& all search engines, as far as I can tell) still point to plcrashreporter.org, which appears to be dead or perhaps hijacked.
