### ISSUE TITLE
PLCrashReporter v1.8.1 crashlogs are not getting generated

### ISSUE THREAD

**Issue by hemaks123** [microsoft/plcrashreporter#160]
Hey team,

I have integrated PLCrashReporterv1.8.1 to the project and simulated some crashes. But the reporter always says no pending reports even after the crashes. I added the framework from the PLCrashReporter-1.8.1.zip-> iOS framework. Could anyone please guide me the framework integration if I am missing anything from frameworks integration?

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! 
Could you please share the code snippet how you use PLCrashReporter?
Also, could you please confirm that you perform a crash without attaching a debugger?

**Comment by hemaks123** [comment]
[CrashReporterSwiftUISample.zip](https://github.com/microsoft/plcrashreporter/files/5716803/CrashReporterSwiftUISample.zip)
I am simulating the crashes in simulator. Is the framework is different for iOS and iOS simulator to get the crashes?
I have added the framework in PLCrashReporter-1.8.1-> iOS Framework->CrashReporter.framework. Please guide me if I am missing anything in framework integration.

**Comment by DmitriyKirakosyan** [comment]
Hi @hemaks123,

I was able to get the crash report using your sample. Please try these steps:
1. Edit the target scheme and uncheck 'Run -> Debug executable'
![Screen Shot 2020-12-22 at 00 42 31](https://user-images.githubusercontent.com/536497/102824819-98d05680-43ee-11eb-983e-012cc6048b12.png)
2. Run the app on a simulator. Once the app is crashed, run it again
3. Observe the message "crash report is handled" in the output.

Second repro option:
1. Build the app and run it on a simulator using Xcode
2. Then open the app again on the simulator the app was installed on. This way the app won't be debugged and the crash will be saved successfully
3. Run the app again, but this time from Xcode again
4. Observe the message "crash report is handled" in the output.

Note, that the crash report won't be saved when the debugger is attached.

**Comment by hemaks123** [comment]
Hi DmitriyKirakosyan,

Great solution..it worked for me!! Thank you for the suggestions.

Thanks ,
Hema
