### ISSUE TITLE
api for setting the crash path

### ISSUE THREAD

**Issue by youbing** [microsoft/plcrashreporter#163]
**Is your feature request related to a problem? Please describe.**
Our app has a sub-process. When the app starts, it will start the sub-process which is a console app. The main app runs in sandbox on MacOS and can find the sandbox path, but the sub-process can not find the sandbox path correctly, so PLCrashReporter cann't write the crash info because of permission issue.

**Describe the solution you'd like**
- (instancetype) initWithConfiguration: (PLCrashReporterConfig *) configuration basePath:(NSString*) basePath {
    return [self initWithBundle: [NSBundle mainBundle] basePath:basePath configuration: configuration];
}

- (id) initWithBundle: (NSBundle *) bundle basePath:(NSString*)basePath configuration: (PLCrashReporterConfig *) configuration {
    NSString *bundleIdentifier = [bundle bundleIdentifier];
    NSString *bundleVersion = [[bundle infoDictionary] objectForKey: (NSString *) kCFBundleVersionKey];
    NSString *bundleMarketingVersion = [[bundle infoDictionary] objectForKey: @"CFBundleShortVersionString"];
    
    /* Verify that the identifier is available */
    if (bundleIdentifier == nil) {
        const char *progname = getprogname();
        if (progname == NULL) {
            [NSException raise: PLCrashReporterException format: @"Can not determine process identifier or process name"];
            return nil;
        }

        PLCR_LOG("Warning -- bundle identifier, using process name %s", progname);
        bundleIdentifier = [NSString stringWithUTF8String: progname];
    }

    /* Verify that the version is available */
    if (bundleVersion == nil) {
        PLCR_LOG("Warning -- bundle version unavailable");
        bundleVersion = @"";
    }
    
    return [self initWithApplicationIdentifier: bundleIdentifier appVersion: bundleVersion appMarketingVersion:bundleMarketingVersion basePath:basePath configuration: configuration];
}

- (id) initWithApplicationIdentifier: (NSString *) applicationIdentifier appVersion: (NSString *) applicationVersion appMarketingVersion: (NSString *) applicationMarketingVersion basePath:(NSString*)basePath configuration: (PLCrashReporterConfig *) configuration {
    /* Initialize our superclass */
    if ((self = [super init]) == nil)
        return nil;

    /* Save the configuration */
    _config = configuration;
    _applicationIdentifier = applicationIdentifier;
    _applicationVersion = applicationVersion;
    _applicationMarketingVersion = applicationMarketingVersion;
    
    /* No occurances of '/' should ever be in a bundle ID, but just to be safe, we escape them */
    NSString *appIdPath = [applicationIdentifier stringByReplacingOccurrencesOfString: @"/" withString: @"_"];
    
    //NSArray *paths = NSSearchPathForDirectoriesInDomains(NSCachesDirectory, NSUserDomainMask, YES);
    //NSString *cacheDir = [paths objectAtIndex: 0];
    _crashReportDirectory = [[basePath stringByAppendingPathComponent: PLCRASH_CACHE_DIR] stringByAppendingPathComponent: appIdPath];
    
    return self;
}

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by russelarms** [comment]
Hi @youbing! Thank you for opening a feature request!
You already provided the code, would you mind opening a Pull Request with the change? It'll help us speed up the process of testing and approval a bit.

**Comment by Jamminroot** [comment]
Hey @youbing, great job adding this API, thanks! Can I've looked at the PR, and couldn't help myself but noticing those minor changes in format of your code compared to the rest of the code in PLCR. Would you mind addressing those? Otherwise I can do that myself (did not do anything since it's your PR on the first place)

**Comment by Jamminroot** [comment]
Hey again, @youbing, sorry it took a while - have a look at the current state of the PR, and share your thoughts.

**Comment by youbing** [comment]
Hi Jamminroot , I have submitted pull request - https://github.com/microsoft/plcrashreporter/pull/164, and the pull request has been reviewed by Microsoft engineers.

**Comment by Jamminroot** [comment]
@youbing yeah, we did review it, and after discussion decided to move basePath property to PLCR Configuration class (which actually would look cleaner imo). Please. have a look at the new PR: #167

**Comment by Jamminroot** [comment]
I've merged the PR, so those changes are going to be included in the next release. Closing the issue now, but feel free to reopened whether it's required.
