### ISSUE TITLE
Include tools in all 3 type of release

### ISSUE THREAD

**Issue by Cyberbeni** [microsoft/plcrashreporter#165]
Currently only the "regular" release contains plcrashutil, so the people who want to use one of the other 2 choices, need to download both zips. It would be nice to have the tools included in all 3 zips

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! 
It makes sense. We will discuss it with the team.

**Comment by MatkovIvan** [comment]
I've updated our packaging scripts to include it in all archives. It will be available with the next release (no ETA).
