### ISSUE TITLE
how can I debugger

### ISSUE THREAD

**Issue by Wbqqqq** [microsoft/plcrashreporter#173]
Hello dear author, I am a rookie. I just started to with the exception collection development of IOS.  
Recently, I have consulted a lot of materials, and have some understanding of the concepts of Mach exception and UNIX signal and the theory of capture.
I want to know  how to debug with Xcode after downloading it? For example, I want to see how mach exceptions and semaphores are intercepted, and how they are written into data. Thank you very much.

**Comment by MatkovIvan** [comment]
Hi @Wbqqqq,

Thanks for getting in touch! As you already know Xcode debugger does not interact well with crash reporters, so you cannot use it in some cases. However, logging works well 😄  so you can play with it. See `PLCR_LOG` as example.

**Comment by MatkovIvan** [comment]
Feel free to reopen/comment if you have more questions.
