### ISSUE TITLE
Swift Documentation

### ISSUE THREAD

**Issue by willm132** [microsoft/plcrashreporter#182]
Is there any documentation for getting this to work in a Swift project?

**Comment by russelarms** [comment]
Hi @willm132!
There's no Swift documentation for PLCR at the moment.
You can try to use these Obj-C snippets, and get back to us if you face any difficulties adopting them: https://github.com/microsoft/plcrashreporter#example
Another way is to use [App Center SDK](https://github.com/Microsoft/AppCenter-SDK-Apple), which uses PLCR for crash handling under the hood. It has thorough Swift documentation.

**Comment by DmitriyKirakosyan** [comment]
We've added a swift example here: https://github.com/microsoft/plcrashreporter#swift, so I'm closing this feature request.
