### ISSUE TITLE
enableCrashReporterAndReturnError crashed after init

### ISSUE THREAD

**Issue by magic3584** [microsoft/plcrashreporter#183]
### **Repro Steps**

Please list the steps used to reproduce your issue.

1. pod 'PLCrashReporter', '1.8.1'
2.
```` objective-c
PLCrashReporterConfig *config = [[PLCrashReporterConfig alloc] initWithSignalHandlerType: PLCrashReporterSignalHandlerTypeMach
                                                                           symbolicationStrategy: PLCrashReporterSymbolicationStrategyAll];
self.crashReporter = [[PLCrashReporter alloc] initWithConfiguration: config];

 // Enable the Crash Reporter.
NSError *error;
 if (![self.crashReporter enableCrashReporterAndReturnError: &error]) {
      NSLog(@"Warning: Could not enable crash reporter: %@", error);
}
````
3. crash when **enableCrashReporterAndReturnError**, both run in Debug&Release scheme:
**Message from debugger: Terminated due to signal 5**

### **Details**

1. Which SDK version are you using?
1.8.1

2. Which OS version did you experience the issue on?
iOS 14.4

3. Which CocoaPods/Carthage/Xcode version are you using?
CocoaPods 1.10.0

4. What device version did you see this error on? Were you using an emulator or a physical device?
Xs Device

5. What language are you using?
    - [x] Objective C
    - [ ] Swift
6. What third party libraries are you using?

**Comment by BibekUXCam** [comment]
Was this issue fixed?

**Comment by DmitriyKirakosyan** [comment]
Hi @BibekUXCam 

Are you facing the same issue? Could you please provide some information about SDK version, cocoapods version etc, or create a new issue filling out the template?

@magic3584 Were you able to resolve the issue? Could you please share a few words about the problem and how it was fixed?

**Comment by magic3584** [comment]
@BibekUXCam 
Hi, please see this function's comment [debugger_should_exit](https://github.com/microsoft/plcrashreporter/blob/b7b88ee14bbc25ce408ae05464cb6f1cdd747948/Other%20Sources/Crash%20Demo/main.m#L117)

@DmitriyKirakosyan 
It works fine without debug mode, thanks for building this helpful tool~
