### ISSUE TITLE
How to add custom data in report with protocol buffer?

### ISSUE THREAD

**Issue by magic3584** [microsoft/plcrashreporter#184]
### **Description**

I wanna add some custom data in report with protocol buffer

### **Details**

1. Which SDK version are you using?
1.8.1

2. What language are you using?
    - [x] Objective C
    - [ ] Swift

**Comment by russelarms** [comment]
Hi @magic3584, there's a public API for this `PLCrashReporter.setCustomData`, e.g.:
```
PLCrashReporter *crashReporter = [[PLCrashReporter alloc] initWithConfiguration:[[PLCrashReporterConfig alloc] initWithSignalHandlerType:PLCrashReporterSignalHandlerTypeBSD symbolicationStrategy:PLCrashReporterSymbolicationStrategyAll]];

NSData *customData = [@"DummyInfo" dataUsingEncoding:NSUTF8StringEncoding];
[crashReporter setCustomData:customData];
```
After the crash happened:
```
NSError *error;
NSData *crashData = [crashReporter loadPendingCrashReportDataAndReturnError: &error];
PLCrashReport *report = [[PLCrashReport alloc] initWithData: crashData error: &error];
NSLog(@"%@", report.customData);
```

**Comment by magic3584** [comment]
@russelarms 
Thanks, but I cannot set
<img width="905" alt="WX20210607-142221@2x" src="https://user-images.githubusercontent.com/6275110/120968728-cee67480-c79b-11eb-9fd9-6275591844d8.png">

**Comment by russelarms** [comment]
> And I wanna know if I did not purge using [self.crashReporter purgePendingCrashReport] , will it be covered when next crash?

If you don't purge the report and your next session won't crash `[crashReporter loadPendingCrashReportDataAndReturnError: &error];` will return the same crash.
If during the next session you will have another crash, `[crashReporter loadPendingCrashReportDataAndReturnError: &error];` will return the new one.

**Comment by magic3584** [comment]
Thanks guy, I will save as file to save more crash reports.
