### ISSUE TITLE
Cannot build PLCReporter on macOS 10.15

### ISSUE THREAD

**Issue by yousefhamza** [microsoft/plcrashreporter#19]
Hi all 👋

I've been trying to rebuild this on macOS 10.15 but there's an issues that is related to macOS 10.15 and some issues that are not.

## Specific to macOS 10.15:
* `protoc-c` included with the repo doesn't work anymore because it's 32 bit 
> **My fix:** I had to reinstall it with `brew` and modify many other things

## Not specific to macOS 10.15:
* The product directory and name for both the `CrashReporter-iOS-Device` and `CrashRepoter-iOS-Simulator` is the (inherited from `CrashReporter-iOS`) because it's based in a build setting  called `EFFECTIVE_PLATFORM_NAME` and the name set there `iphoneos` is not the same as the names expected from `lipo` which are  `iPhoneOS` and `iPhoneSimulator`

> **My fix:** Added `EFFECTIVE_PLATFORM_NAME` in `CrashReporter-iOS-Device` and `CrashReporter-iOS-Simulator` with values `iPhoneOS` and `iPhoneSimulator` respectively.

* When `Disk Image` is built for simulator `CrashReporter-iOS-Device` build for "`i386` and `x86_64`" only is the same as `CrashReporter-iOS-Simulator` which cause `lipo` to throw and error because it tries to combine 2 binaries with the same architecture (the opposite happens when trying to build for device)
> **My fix:** Removed `CrashReporter-iOS-Device` from the dependencies of `Disk Image` and built it alone to device then built `Disk Image` for Simulator.
> This is not really a fix and the common practice ([IMHO](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwiCrs6NzfPjAhUNfxoKHTUlBy4QFjAAegQIARAB&url=https%3A%2F%2Finstabug.com%2Fblog%2Fios-binary-framework%2F&usg=AOvVaw0JPnqs6rIeghrz0zewNM6e)) for building fat binary is that the aggregate target itself build with `xcodebuild` both targets for simulator and for device then combine them not depend on Xcode to build them.

**Comment by clpolet** [comment]
@yousefhamza my apologize for the poor followup on this issue. We'll be blocking some times really soon to get your contribution in.

**Comment by clpolet** [comment]
It's very unfortunate but the work was delayed.

**Comment by yousefhamza** [comment]
@clpolet anything we do from our side?

**Comment by ozzyremi** [comment]
When will this fix merged to master branch?

**Comment by annakocheshkova** [comment]
Hi there @yousefhamza!
It was decided not to keep binaries in the repo so now it is a submodule + additional brew dependency.
The updated version is in `develop` branch of our fork and now we are in the process of merging this into official repository. 
You can see the full list of changes in our `CHANGELOG` file in the root of the repo.

In any case, thank you very much for your contribution, we really appreciate it!
