### ISSUE TITLE
"Found an unexpected Mach-O header code: 0x72613c21" when adding as XCFramework

### ISSUE THREAD

**Issue by xw1097** [microsoft/plcrashreporter#192]
### **Description**

When using XCframework downloaded from the release page and dragged into my project, archive was successful, but "validate" fails with  "Found an unexpected Mach-O header code: 0x72613c21"

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Prep a very basic iOS project to integrate with plcrashreporter: for example, https://github.com/xw1097/onTheMap/
2. download "PLCrashReporter-XCFramework-1.9.0.zip" from [release page](https://github.com/microsoft/plcrashreporter/releases/tag/1.9.0) and unzip it.
3. Drag the xcframework into the project target -> "Framework, Library, and Embeded content"
     
<img width="872" alt="Screen Shot 2021-06-23 at 9 41 43 PM" src="https://user-images.githubusercontent.com/1831628/123203842-ce243280-d46b-11eb-8b6a-136431b90b53.png">

4. Open the Xcode project and choose device as "Any iOS Device Arm64" so that we could archive.
5. In the project setting page, make sure the target "signing and & capabilities" page have a valid team to be able to archive. Also make sure to choose a unique bundle id.
6. Xcode, Project -> Archive.
7. Once archive finishes, it will pop up a windows and you can click on validate button. And you will see the error.
   attached log files zip for the validation step.
[OnTheMap_2021-06-23_19-32-52.632.xcdistributionlogs.zip](https://github.com/microsoft/plcrashreporter/files/6705874/OnTheMap_2021-06-23_19-32-52.632.xcdistributionlogs.zip)

### **Details**

1. Which SDK version are you using?   1.9.0/1.8.1 - (tried even earlier version but macOS minimal deployment mismatch)
2. Which OS version did you experience the issue on? 11.3
3. Which CocoaPods/Carthage/Xcode version are you using? Xcode 12.5 12E262
4. What device version did you see this error on? Were you using an emulator or a physical device? - simulator physical deployment is successful, once archive validation failure 
5. What language are you using?
    - [ ] Objective C
    - [ X ] Swift
6. What third party libraries are you using? - None

**Comment by MatkovIvan** [comment]
Hi @xw1097, it's static framework, it should not be embedded. Change the option to "Do Not Embed" in "Framework, Library, and Embeded content"

**Comment by xw1097** [comment]
it works after I changed the settings, thanks for the tips.
