### ISSUE TITLE
Wrong XCFramework asset name in GH releases

### ISSUE THREAD

**Issue by buranmert** [microsoft/plcrashreporter#197]
### **Description**

[Starting from `v0.38.0` carthage supports pre-built `.xcframework` binaries](https://github.com/Carthage/Carthage/releases/tag/0.38.0).
As explained in their release notes, in order to support this feature Github release assets should be named
1. `PLCrashReporter-1.9.0.carthage.framework.zip`
2. `PLCrashReporter-1.9.0.carthage.xcframework.zip`

However, `PLCrashReporter` has `PLCrashReporter-XCFramework-1.9.0.zip` as its xcframework asset in the Github releases.

That results in `carthage` fetching `.framework` even if `--use-xcframeworks` flag is used.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. In Terminal `echo "github \"microsoft/plcrashreporter\"" >> Cartfile && carthage update`

**Expected result**

`CrashReporter.xcframework` will be in `Carthage/Build` so that I can use it in my project.

**Actual result**

`carthage` downloads `PLCrashReporter-1.9.0.carthage.framework.zip` and I have `CrashReporter.framework` per platform:
```
{iOS/tvOS/Mac}/CrashReporter.framework
```

### **Details**

1. Which SDK version are you using? **`1.9.0`**
2. Which OS version did you experience the issue on? **Every OS version**
3. Which CocoaPods/Carthage/Xcode version are you using? **Carthage 0.38.0**
4. What device version did you see this error on? Were you using an emulator or a physical device? **This is a pre-compile-time issue**
5. What language are you using?
    - [x] Objective C
    - [x] Swift
6. What third party libraries are you using? **None**

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! 
For now, the `PLCrashReporter` doesn't support distribution `XCFramework` via `Carthage`. I will label this as a feature request.

**Comment by buranmert** [comment]
hi @AnastasiaKubova 👋 thanks for the quick response!

i'm seeing [PLCrashReporter-XCFramework-1.9.0.zip](https://github.com/microsoft/plcrashreporter/releases/download/1.9.0/PLCrashReporter-XCFramework-1.9.0.zip) asset in 1.9.0 release and i thought renaming it would be enough.

what is this `.xcframework` for? should i avoid using it?

**Comment by DmitriyKirakosyan** [comment]
Hi @buranmert 

The `PLCrashReporter-XCFramework-*.zip ` is totally fine and you can use it in your project.
Ideally, we would want to replace all integration methods to use `.xcframework`, however it is not always possible at this moment. For example, we can't ship `.xcframework` with Cocoapods because PLCrashReporter has static and dynamic libraries in one framework and this behaviour is not currently supported by Cocoapods (see [CocoaPods + mixed (static+dynamic for mac) XCFramework issue](https://github.com/CocoaPods/CocoaPods/issues/10262)).

In case of Carthage, I guess we can do it, but we will need to perform integration tests and make sure it doesn't break anything.

**Comment by buranmert** [comment]
hey @DmitriyKirakosyan 👋 

we are using `PLCrashReporter` in [Datadog iOS SDK](https://github.com/DataDog/dd-sdk-ios/).
Swift Package Manager and Cocoapods don't cause problems so far but Carthage case is tricky as `DatadogSDK` requires `--use-xcframeworks` flag and `PLCR v1.9.0` keeps using `.framework` despite that flag.

as a workaround [i pinned `PLCR` to v1.8.1](https://github.com/DataDog/dd-sdk-ios/blob/master/Cartfile#L2) which falls back to building from source and produce `.xcframework`, instead of failing as v1.9.0 does.

can you please update this issue once you make the changes so that i can change my `Cartfile`?

**Comment by DmitriyKirakosyan** [comment]
Hi @buranmert 

We tested Carthage with xcframeworks and it looks working on carthage of version 0.38.
However, it seems to have some issues when there are two frameworks present in repo with `.carthage` in its name at the same time (normal and xcframeowork). I think we are good to move to xcframeworks for carthage, but we will do it next release to avoid modifying the current release.

I will keep this issue open until we release next version.

**Comment by DmitriyKirakosyan** [comment]
Hi @buranmert 

New release of PLCrashReporter was published today. You can now integrate XCFramework binary via Carthage.
I'm closing this issue.
