### ISSUE TITLE
arm64e stack trace displays ???

### ISSUE THREAD

**Issue by shradda02** [microsoft/plcrashreporter#20]
I integrated the latest CrashReporter.framework for iOS available from release 1.2.3-rc1, but the stack trace from an arm64e (iPhone XS) device still display ??? for library names and the addresses are 0. I thought this fork supports arm64e devices. Am I missing something here? Thanks.

**Comment by salukurian** [comment]
@MatkovIvan just wanted to check if we have support for arm64e and what version PLCrashReporter are we currently on ?

**Comment by MatkovIvan** [comment]
Yes, it's supported since `1.4.0` (see [changelog](https://github.com/microsoft/plcrashreporter/blob/master/CHANGELOG.md)). We're tracking this bug to fix it in a future release.

**Comment by salukurian** [comment]
Thanks but when we tried to look at the formulated crash log on newer iOS models it failed to construct proper crash report with ?? shown for system libraries, https://github.com/microsoft/PLCrashReporter-Fork/pull/15  had a fix for this, don't know if are aware of this
