### ISSUE TITLE
How can we save non-fatal error and information?

### ISSUE THREAD

**Issue by DemetAkyol** [microsoft/plcrashreporter#200]
Controlling crashes with the crashReporter.hasPendingCrashReport()  method is included in the document, but how can we drop non-fatal errors or notifications here?

We can record with Crashlytics.crashlytics().record(error: error) for Firebase, I couldn't see an example of this?

Can we detect recorded messages like crashes?

**Comment by AnatolyPristensky** [comment]
Hello @DemetAkyol!  Thank you for getting in touch with us!
We will investigate your question and reply with results.

**Comment by DmitriyKirakosyan** [comment]
Hi @DemetAkyol 

PLCrashReporter only allows you to retrieve the crash happened in the previous run of application, and it will be a fatal one. PLCrashReporter doesn't save any handled or informational logs.

Please check this example of using the PLCrashReporter : https://github.com/microsoft/plcrashreporter#example.

If you need an ability to collect, filter and send crash logs to backend, you may want to check out [App Center SDK](https://github.com/microsoft/appcenter-sdk-apple), which uses PLCrashReporter under the hood and provides such API.

I'm closing this issue, but feel free to reopen it if you have additional questions.
