### ISSUE TITLE
Is dSYM file configuration required?

### ISSUE THREAD

**Issue by DemetAkyol** [microsoft/plcrashreporter#201]
In case of crash, I want to send them to another place like graylog. A file like dSYM is required every time a release is released?

**Comment by DmitriyKirakosyan** [comment]
Hi @DemetAkyol 

Thank you for reaching out to us!

Updating file `dSYM` is required when your code is changed. So, if the release includes some changes in code, then yes, you will need a new dSYM in order to parse the stack traces correctly.

Closing this issue but feel free to reopen if you have additional questions.

**Comment by DemetAkyol** [comment]
Hi @DmitriyKirakosyan 

Thank you very much for your reply and support.

Could you share a document or explanation showing how we can create and upload the dSYM file?
Is dSYM taken from xcode, how is it loaded?

thanks a lot again.

**Comment by DemetAkyol** [comment]
Hi @DmitriyKirakosyan

Should I open a new issue about how to import and load dSYM?

**Comment by DmitriyKirakosyan** [comment]
Here are a frew links for you about dSYM:
- [Building Your App to Include Debugging Information
](https://developer.apple.com/documentation/xcode/building-your-app-to-include-debugging-information)
- [What's the dSYM and how to use it? (iOS SDK)](https://stackoverflow.com/questions/3656391/whats-the-dsym-and-how-to-use-it-ios-sdk)
- [PLCrashReporter/Decoding Crash Reports](https://github.com/microsoft/plcrashreporter#decoding-crash-reports)

Uploading the file depends on the backend you use. In case of App Center, there is an instruction on how to create and upload `dSYM` file [here](https://docs.microsoft.com/en-us/appcenter/diagnostics/ios-symbolication).

**Comment by DemetAkyol** [comment]
Hi @DmitriyKirakosyan 
Is the Decoding Crash Reports part in the document used for symbolicate?
Is the symbolicate operation performed and sent to the server side?
Can you explain what plcrashutil is and how to use it?

**Comment by DmitriyKirakosyan** [comment]
Hi @DemetAkyol 

> Is the Decoding Crash Reports part in the document used for symbolicate?

It describes how you can convert the file produced by PLCrashReport to iOS crash log file (`.crash`).
Once you get the `.crash` file, you can sybmolicate it using dSYM file. Read more about sybmolicating apple crash log in [Adding Identifiable Symbol Names to a Crash Report](https://developer.apple.com/documentation/xcode/adding-identifiable-symbol-names-to-a-crash-report).

> Is the symbolicate operation performed and sent to the server side?

No, PLCrashReporter lib doesn't send anything over the network. You should do it manually in your app.

> Can you explain what plcrashutil is and how to use it?

Just call `plcrashutil` from shell and you will see a hint on how to use the command. Generally your command would look like `plcrashutil convert --format=iphone example_report.plcrash`.
In case you want to convert the file in runtime before sending to your server, you can use the lib API to do so:
```objc
PLCrashReportTextFormat textFormat = PLCrashReportTextFormatiOS;
NSString* iosCrashReport = [PLCrashReportTextFormatter stringValueForCrashReport: crashReport withTextFormat: textFormat];
```

**Comment by DemetAkyol** [comment]
How does PLCrashReport generate .crash file?
Doesn't it just generate iosCrashReport as you showed? I understood that it only generates crash data.
  How can I access this .crash file? Should I send this .crash file to the server? Should I resolve this and the dSYM on the server side with plcrashutil?

**Comment by DmitriyKirakosyan** [comment]
hi @DemetAkyol 

> How does PLCrashReport generate .crash file?

It generates `.plcrash` file. Once your app is crashes, PLCrashReporter catches the crash and stores the crash data in file with extension `.plcrash` on disk. Next launch of the application it allows you to process the crash data.

> Doesn't it just generate iosCrashReport as you showed? I understood that it only generates crash data.

You convert the crash data to ios crash report (`.crash`) manually when processing the crash. Please check [the example](https://github.com/microsoft/plcrashreporter#example). 

> How can I access this .crash file? Should I send this .crash file to the server? Should I resolve this and the dSYM on the server side with plcrashutil?

You are accessing file data on second launch of the application, using `[crashReporter loadPendingCrashReportDataAndReturnError: &error]`. Then you convert it to `.crash` using `[PLCrashReportTextFormatter stringValueForCrashReport: report withTextFormat: PLCrashReportTextFormatiOS]`, and after that you have a `NSString` which represents an ios crash report (`.crash`). You can send it to your server. Then you can symbolicate it following the apple's docs.

**Comment by DemetAkyol** [comment]
Hi @DmitriyKirakosyan 
When I convert the crash data to NSString, it is so big that I can't post to the server side, how can we handle this?
"Then you can symbolicate it following the apple's docs." is that the document you're talking about; https://developer.apple.com/documentation/xcode/adding-identifiable-symbol-names-to-a-crash-report

Here again, I understand that we need dSYM to analyze. So, is it possible for me to do this on a server in a windows environment?

**Comment by DmitriyKirakosyan** [comment]
> When I convert the crash data to NSString, it is so big that I can't post to the server side, how can we handle this?

You can send it in POST, as binary, or as a plain text. Please refer to Apple documentation on how to upload a file in iOS, eg. [Uploading Data to a Website](https://developer.apple.com/documentation/foundation/url_loading_system/uploading_data_to_a_website).

> "Then you can symbolicate it following the apple's docs." is that the document you're talking about; https://developer.apple.com/documentation/xcode/adding-identifiable-symbol-names-to-a-crash-report

Yes

> Here again, I understand that we need dSYM to analyze. So, is it possible for me to do this on a server in a windows environment?

I think you can't do it on Windows. The tools allowing to symbolicate the file are available on Mac environment only. However there might be some third party solutions for windows which I'm not aware of.
