### ISSUE TITLE
Is Incident Identifier the same for Apple crash report and PLCrashReporter?

### ISSUE THREAD

**Issue by xwang-hbo** [microsoft/plcrashreporter#217]
### **Description**

I'm trying to compare apple crash report and PLCrash report. My use case is that given an apple crash report, use the incident identifier and look up backend end event(which contains PLCrashReporter uuidref).

The code I have for grabbing uuid from PLCrashReporter is 
```
let plcrashuuid: String  = CFUUIDCreateString(nil, crashReport.uuidRef) as String;
// then I report a crash event to my own backend with plcrashuuid as a field inside of the event.
```

### **Repro Steps**

1. Run an sample app on physical phone that has PLCrashReporter integrated and intentionally crash the app by some exception(e.g. access out of bound array). 
2. Your iphone has "Analytics data" in setting, grab that and see the incident identifier
3. load your app again and PLCrashReporter should get uuid and compare that UUID with apple's incident identifier, they're different.

### **Details**

1. Which SDK version are you using?   1.9
2. Which OS version did you experience the issue on? iOS 12
3. Which CocoaPods/Carthage/Xcode version are you using? Xcode 12.4, not using CocaPods
4. What device version did you see this error on? Were you using an emulator or a physical device? Iphone6 physical phone
5. What language are you using?
    - [ ] Swift
6. What third party libraries are you using? none.

**Comment by AnastasiaKubova** [comment]
Your `UUID`s are different because `PLCrashReporter` itself generates an error report. `UUID` is generated [here](https://github.com/microsoft/plcrashreporter/blob/b7b88ee14bbc25ce408ae05464cb6f1cdd747948/Source/PLCrashLogWriter.m#L319).

**Comment by xwang-hbo** [comment]
great, thx for confirming, for a long time I thought PLCrashReporter would load up Apple's incident Id. But seems like it just does its own signal handling and just format the same as apple(which makes me think it loads apple's incident Id)
