### ISSUE TITLE
Crash Report not generated

### ISSUE THREAD

**Issue by ozzyremi** [microsoft/plcrashreporter#22]
When I run DemoCrash in my system. Even-though app is crashed I never get crash report. What setting does this DemoCrash depends on?
MacOS:  10.15 (19A583)
Xcode: 11.1

**Comment by MatkovIvan** [comment]
Hi @ozzyremi,

We're actively working on macOS 10.15 support.
We'll let you know when it is ready for use.

**Comment by MatkovIvan** [comment]
It should be fixed on `master` now
