### ISSUE TITLE
App "terminated due to signal 5"

### ISSUE THREAD

**Issue by chung-lai** [microsoft/plcrashreporter#220]
### **Description**

After installing the package through Swift package manager in XCode, my app crashed due to "terminated due to signal 5" inside `enableCrashReporterAndReturnError`. Similar problem seem to be reported on https://githubmemory.com/repo/microsoft/plcrashreporter/issues/183

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Install latest release (1.10.0) with Swift package manager with XCode 13.0
2. Follow the documentation to call `enableCrashReporterAndReturnError`
3. Crash with "terminated due to signal 5"

### **Details**

1. Which SDK version are you using? 1.10.0
2. Which OS version did you experience the issue on? 15.0
3. Which CocoaPods/Carthage/Xcode version are you using? XCode 13.0
4. What device version did you see this error on? Were you using an emulator or a physical device? iOS 15.0
5. What language are you using?
    - [ ] Objective C
    - [X] Swift
6. What third party libraries are you using?

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us!
I am trying to reproduce this issue based on your steps but for me all work well.
- Could you please clarify did you crash the app after `CrashReporter` initialization? If so, then could you please make sure that you crash your app without a debugger? `CrashReporter` doesn't catch crashes in debug mode.
- Did you check this issue on an empty test app?
- Do you have a chance to share a crash report or stack traces?

**Comment by AnastasiaKubova** [comment]
We haven’t heard from you in a while so I’m closing this issue but feel free to reopen this issue if you have additional questions.

**Comment by chung-lai** [comment]
Thank you for the follow up. I'm still experiencing the issue and I have created a sample project.

The way to reproduce the crash is to run the app in debugger and the console will output "Message from debugger: Terminated due to signal 5". I couldn't get a stack trace with that.

[PLCrasherCrash.zip](https://github.com/microsoft/plcrashreporter/files/7630006/PLCrasherCrash.zip)

**Comment by chung-lai** [comment]
> Hi! Thanks for getting in touch with us! I am trying to reproduce this issue based on your steps but for me all work well.
> 
> * Could you please clarify did you crash the app after `CrashReporter` initialization? If so, then could you please make sure that you crash your app without a debugger? `CrashReporter` doesn't catch crashes in debug mode.
> * Did you check this issue on an empty test app?
> * Do you have a chance to share a crash report or stack traces?

1) The crash starts happening after integrating with the PLCrashReporter framework at the initialization step when it calls `enableAndReturnError`
2) Uploaded a empty test app to reprod the issue
3) Unfortunately, it doesn't show any stack trace, it simply quit the app

**Comment by chung-lai** [comment]
@AnastasiaKubova, I couldn't reopen the issue. Thanks

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for the details. `CrashReporter` doesn't catch crashes in debug mode.

**Comment by chung-lai** [comment]
Thanks. I understand that. I'm not trying to catch a crash, it's the framework causing the app to terminate itself. The app doesn't start in debug mode after importing and initializing the CrashReporter framework.

**Comment by chung-lai** [comment]
Looks like it's also being reported here: https://github.com/microsoft/plcrashreporter/issues/183

**Comment by chung-lai** [comment]
From reading #183, we should not use this framework in debugger?

**Comment by DmitriyKirakosyan** [comment]
Hi @chung-lai , yes PLCrashReporter only works when you run the app without a debugger, so you need to enable it when the debugger is not attached only. For doing so you can either check if debugger is attached, like we do in AppCenter SDK:
- [Enable PLCrashReporter if debugger is not atached](https://github.com/microsoft/appcenter-sdk-apple/blob/942232b573c9c9987ae5d16df95c303c517fb9f0/AppCenterCrashes/AppCenterCrashes/MSACCrashes.mm#L731)
- [This is how we check wether debugger is attached](https://github.com/microsoft/appcenter-sdk-apple/blob/fa8c7d353a4f7819763816a026666320f7315d45/AppCenter/AppCenter/MSACAppCenter.m#L208)

or use a compilation condition `#if DEBUG`.

**Comment by chung-lai** [comment]
Great! Thank you for helping me out on this, @DmitriyKirakosyan @AnastasiaKubova!

May be this is already mentioned in the documentation but I thought I read through it. If it's not in the doc yet, may worth calling this piece of information out 😄 Thanks!
