### ISSUE TITLE
what is the difference between PLCrashReporterSignalHandlerTypeBSD and PLCrashReporterSignalHandlerTypeMach

### ISSUE THREAD

**Issue by PJLX** [microsoft/plcrashreporter#223]
I do not know the difference between PLCrashReporterSignalHandlerTypeBSD and PLCrashReporterSignalHandlerTypeMach.
I am a Mac developer, which kind should I use 
thanks

**Comment by aleksandr-dorofeev** [comment]
Hi @PJLX 
Thanks for getting in touch with us! `PLCrashReporterSignalHandlerTypeBSD` allow handle in-process exceptions only, and `PLCrashReporterSignalHandlerTypeMach` allow handle both in-process and out-of-process exceptions. We recommend to use `PLCrashReporterSignalHandlerTypeMach` ([see comment](https://github.com/microsoft/plcrashreporter/issues/202#issuecomment-897619298)).
Also you can find description about it [here](https://github.com/microsoft/plcrashreporter/blob/master/Source/PLCrashReporterConfig.h#L41).

**Comment by PJLX** [comment]
> Hi @PJLX
> Thanks for getting in touch with us!
> Please see the comments in [code](https://github.com/microsoft/plcrashreporter/blob/master/Source/PLCrashReporterConfig.h#L41) to understand the difference between these handler types.
> In general it is recommended to use `PLCrashReporterSignalHandlerTypeMach`, however it doesn't work with a debugger ([see this description](https://github.com/microsoft/plcrashreporter/blob/b7b88ee14bbc25ce408ae05464cb6f1cdd747948/Source/PLCrashReporterConfig.h#L70)).

**Comment by PJLX** [comment]
> Hi @PJLX
> Thanks for getting in touch with us!
> Please see the comments in [code](https://github.com/microsoft/plcrashreporter/blob/master/Source/PLCrashReporterConfig.h#L41) to understand the difference between these handler types.
> In general it is recommended to use `PLCrashReporterSignalHandlerTypeMach`, however it doesn't work with a debugger ([see this description](https://github.com/microsoft/plcrashreporter/blob/b7b88ee14bbc25ce408ae05464cb6f1cdd747948/Source/PLCrashReporterConfig.h#L70)).

thanks
