### ISSUE TITLE
"Implicit conversion loses integer precision" warnings when building swift package for ios device/simulator

### ISSUE THREAD

**Issue by BlixLT** [microsoft/plcrashreporter#225]
### **Description**

We are trying to get rid of all warnings in our project and noticed some in plcrashreporter swift package. Hopefully you will be able to fix them in the future. Thanks.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Open swift Package (Package.swift) with Xcode
2. Build it for iOS device/Simulator (it doesn't happen when building for macOS - there are no such warnings)
3. ~40 warnings similar to `protobuf-c.c:447:27: Implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'uint32_t' (aka 'unsigned int')` appear

### **Details**

1. Which SDK version are you using?
plcrashreport version 1.10.1

2. Which OS version did you experience the issue on?
iOS 15.1 on Device/Simulator

3. Which CocoaPods/Carthage/Xcode version are you using?
Xcode 13.2.1

4. What device version did you see this error on? Were you using an emulator or a physical device?
iPhone X (device), iPhone 13 Pro Max (simulator)

5. What language are you using?
    - [X] Objective C
    - [ ] Swift
    
6. What third party libraries are you using?
None. It can be reproduced simply by building PLCrashReporter's Swift Package project

**Comment by futuretap** [comment]
@DmitriyKirakosyan How can I set these flags when including PLCrashReporter via Swift Package Manager?

**Comment by MatkovIvan** [comment]
All these warnings are from [protobuf-c](https://github.com/protobuf-c/protobuf-c) library. I'm going to update it to latest stable 1.4.0 version (#241), but it still is not fixed there. Even if we DO copy these files manually to our repo (as SwiftPM workaround), we're not going to change it to avoid conflicts during future updates.

**Comment by futuretap** [comment]
This is not completed. The warning still occurs. I understand that protobuf-c is to blame but I'm not sure if they're even aware of the issue.
