### ISSUE TITLE
is this package park of clearlydefined?

### ISSUE THREAD

**Issue by harrieshin** [microsoft/plcrashreporter#227]
### **Description**

We have a component that takes plcrashreporter as a dependency and while our tooling go through compliance checking it flags that microsoft/plcrashreporter isn't part of https://clearlydefined.io/?sort=releaseDate&sortDesc=true 
Should this be part of the publicly accessible open source database? 

### **Repro Steps**

Please list the steps used to reproduce your issue.

1.
2.

### **Details**

1. Which SDK version are you using?
2. Which OS version did you experience the issue on?
3. Which CocoaPods/Carthage/Xcode version are you using?
4. What device version did you see this error on? Were you using an emulator or a physical device?
5. What language are you using?
    - [ ] Objective C
    - [ ] Swift
6. What third party libraries are you using?

**Comment by harrieshin** [comment]
https://github.com/clearlydefined/curated-data/pull/17795 ?

**Comment by aleksandr-dorofeev** [comment]
Hi @harrieshin
PLCrashReporter is open source and free of vulnerabilities. We don't have any plans for adding PLCR to ClearlyDefined at this moment.

I'm closing this issue but feel free to reopen if you have additional questions.
