### ISSUE TITLE
Combining device and simulator frameworks

### ISSUE THREAD

**Issue by liuniuliuniu** [microsoft/plcrashreporter#229]
### **Description**

when I use `Usage: combine-frameworks.sh <device> <simulator> <output>` ，I get a error:  

Appending simulator platform to Info.plist
/Users/xxxx/Desktop/iOS/Info.plist: file does not exist or is not readable or is not a regular file (Error Domain=NSCocoaErrorDomain Code=260 "The file “Info.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/xxx/Desktop/iOS/Info.plist, NSUnderlyingError=0x7fa02a9071a0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}})

### **Repro Steps**

Please list the steps used to reproduce your issue.

1.  build CrashRepoter with Any iOS Device
![image](https://user-images.githubusercontent.com/20876221/158508781-6c55e877-c435-48a2-ac9e-ca07cd8ac66e.png)

2. build CrashReporter with iPhone 13 Pro
![image](https://user-images.githubusercontent.com/20876221/158508876-f1823070-11d0-4845-9282-7df84b810cab.png)
3. then   combine-frameworks.sh <device> <simulator> <output>
4.get Error:

sh combine-frameworks.sh /Users/xxx/Desktop/iOS/真机/CrashReporter.framework /Users/xxx/Desktop/iOS/模拟器/CrashReporter.framework /Users/xxx/Desktop/iOS
Combining device and simulator frameworks
/Users/xxx/Desktop/iOS/真机/CrashReporter.framework -> /Users/xxx/Desktop/iOS/CrashReporter.framework
/Users/xxx/Desktop/iOS/真机/CrashReporter.framework/CrashReporter -> /Users/xxx/Desktop/iOS/CrashReporter.framework/CrashReporter
/Users/xxx/Desktop/iOS/真机/CrashReporter.framework/Headers -> /Users/xxx/Desktop/iOS/CrashReporter.framework/Headers
/Users/xxx/Desktop/iOS/真机/CrashReporter.framework/Headers/PLCrashNamespace.h -> /Users/xxx/Desktop/iOS/CrashReporter.framework/Headers/PLCrashNamespace.h
/Users/xxx/Desktop/iOS/真机/CrashReporter.framework/Headers/PLCrashFeatureConfig.h -> /Users/xxx/Desktop/iOS/CrashReporter.framework/Headers/PLCrashFeatureConfig.h
/Users/xxx/Desktop/iOS/真机/CrashReporter.framework/Headers/PLCrashReporter.h -> /Users/xxx/Desktop/iOS/CrashReporter.framework/Headers/PLCrashReporter.h
/Users/xxx/Desktop/iOS/真机/CrashReporter.framework/Headers/PLCrashReportRegisterInfo.h -> /Users/xxx/Desktop/iOS/CrashReporter.framework/Headers/PLCrashReportRegisterInfo.h
/Users/xxx/Desktop/iOS/真机/CrashReporter.framework/Headers/PLCrashReportBinaryImageInfo.h -> /Users/xxx/Desktop/iOS/CrashReporter.framework/Headers/PLCrashReportBinaryImageInfo.h
/Users/xxx/Desktop/iOS/真机/CrashReporter.framework/Headers/PLCrashReport.h -> /Users/xxx/Desktop/iOS/CrashReporter.framework/Headers/PLCrashReport.h
/Users/xxx/Desktop/iOS/真机/CrashReporter.framework/Headers/PLCrashMacros.h -> /Users/xxx/Desktop/iOS/CrashReporter.framework/Headers/PLCrashMacros.h
/Users/xxx/Desktop/iOS/真机/CrashReporter.framework/Headers/PLCrashReporterConfig.h -> /Users/xxx/Desktop/iOS/CrashReporter.framework/Headers/PLCrashReporterConfig.h
/Users/xxx/Desktop/iOS/真机/CrashReporter.framework/Headers/PLCrashReportMachExceptionInfo.h -> /Users/xxx/Desktop/iOS/CrashReporter.framework/Headers/PLCrashReportMachExceptionInfo.h
/Users/xxx/Desktop/iOS/真机/CrashReporter.framework/Headers/PLCrashReportThreadInfo.h -> /Users/xxx/Desktop/iOS/CrashReporter.framework/Headers/PLCrashReportThreadInfo.h
/Users/xxx/Desktop/iOS/真机/CrashReporter.framework/Headers/PLCrashReportStackFrameInfo.h -> /Users/xxx/Desktop/iOS/CrashReporter.framework/Headers/PLCrashReportStackFrameInfo.h
/Users/xxx/Desktop/iOS/真机/CrashReporter.framework/Headers/PLCrashReportSystemInfo.h -> /Users/xxx/Desktop/iOS/CrashReporter.framework/Headers/PLCrashReportSystemInfo.h
/Users/xxx/Desktop/iOS/真机/CrashReporter.framework/Headers/PLCrashReportExceptionInfo.h -> /Users/xxx/Desktop/iOS/CrashReporter.framework/Headers/PLCrashReportExceptionInfo.h
/Users/xxx/Desktop/iOS/真机/CrashReporter.framework/Headers/PLCrashReportProcessorInfo.h -> /Users/xxx/Desktop/iOS/CrashReporter.framework/Headers/PLCrashReportProcessorInfo.h
/Users/xxx/Desktop/iOS/真机/CrashReporter.framework/Headers/CrashReporter.h -> /Users/xxx/Desktop/iOS/CrashReporter.framework/Headers/CrashReporter.h
/Users/xxx/Desktop/iOS/真机/CrashReporter.framework/Headers/PLCrashReportSignalInfo.h -> /Users/xxx/Desktop/iOS/CrashReporter.framework/Headers/PLCrashReportSignalInfo.h
/Users/xxx/Desktop/iOS/真机/CrashReporter.framework/Headers/PLCrashReportApplicationInfo.h -> /Users/xxx/Desktop/iOS/CrashReporter.framework/Headers/PLCrashReportApplicationInfo.h
/Users/xxx/Desktop/iOS/真机/CrashReporter.framework/Headers/PLCrashReportMachineInfo.h -> /Users/xxx/Desktop/iOS/CrashReporter.framework/Headers/PLCrashReportMachineInfo.h
/Users/xxx/Desktop/iOS/真机/CrashReporter.framework/Headers/PLCrashReportTextFormatter.h -> /Users/xxx/Desktop/iOS/CrashReporter.framework/Headers/PLCrashReportTextFormatter.h
/Users/xxx/Desktop/iOS/真机/CrashReporter.framework/Headers/PLCrashReportFormatter.h -> /Users/xxx/Desktop/iOS/CrashReporter.framework/Headers/PLCrashReportFormatter.h
/Users/xxx/Desktop/iOS/真机/CrashReporter.framework/Headers/PLCrashReportProcessInfo.h -> /Users/xxx/Desktop/iOS/CrashReporter.framework/Headers/PLCrashReportProcessInfo.h
/Users/xxx/Desktop/iOS/真机/CrashReporter.framework/Headers/PLCrashReportSymbolInfo.h -> /Users/xxx/Desktop/iOS/CrashReporter.framework/Headers/PLCrashReportSymbolInfo.h
/Users/xxx/Desktop/iOS/真机/CrashReporter.framework/Modules -> /Users/xxx/Desktop/iOS/CrashReporter.framework/Modules
/Users/xxx/Desktop/iOS/真机/CrashReporter.framework/Modules/module.modulemap -> /Users/xxx/Desktop/iOS/CrashReporter.framework/Modules/module.modulemap
/Users/xxx/Desktop/iOS/真机/CrashReporter.framework/Info.plist -> /Users/xxx/Desktop/iOS/CrashReporter.framework/Info.plist
Removing duplicate architectures (arm64) from library for simulator
Combining device and simulator libraries
Architectures in the fat file: /Users/xxx/Desktop/iOS/CrashReporter are: armv7 armv7s i386 x86_64 arm64 arm64e
Appending simulator platform to Info.plist
/Users/xxx/Desktop/iOS/Info.plist: file does not exist or is not readable or is not a regular file (Error Domain=NSCocoaErrorDomain Code=260 "The file “Info.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/xxx/Desktop/iOS/Info.plist, NSUnderlyingError=0x7fa02a9071a0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}})

**Comment by DmitriyKirakosyan** [comment]
Hi @liuniuliuniu , thank you for reaching out to us!

The `combine-frameworks.sh` script is used in Xcode build phases when building a Universal framework, eg. scheme `CrashReporter iOS Universal` (which is triggered by the main `CrashReporter` scheme). So it will be executed when you build the project in Xcode, and you don't normally need to run the script manually. The args should be paths to frameworks, see:
```
DEVICE_FRAMEWORK="$BUILD_DIR/$CONFIGURATION-iphoneos/$PRODUCT_NAME.framework"
SIMULATOR_FRAMEWORK="$BUILD_DIR/$CONFIGURATION-iphonesimulator/$PRODUCT_NAME.framework"
"$SRCROOT/Scripts/combine-frameworks.sh" "$DEVICE_FRAMEWORK" "$SIMULATOR_FRAMEWORK" "$BUILT_PRODUCTS_DIR/$PRODUCT_NAME.framework"
```

If you still want to run it manually, could you please share more details on what exactly you are trying to achieve?
