### ISSUE TITLE
SDK cannot write log when uncaughtException worked

### ISSUE THREAD

**Issue by alotofleo2** [microsoft/plcrashreporter#230]
### **Description**

Please describe the issue you are facing using the SDK.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. when I was run a exception [NSException raise:@"123" format:@"test"]; ,sdk can run the uncaught_exception_handler ,but plcrash_log_writer_set_exception(&signal_handler_context.writer, exception) writer not worked, I was download device container cannot find the log file; but other signals Reporte is normally , I can find the log in the device container;
2. it is my config code :
    PLCrashReporterConfig *config = [[PLCrashReporterConfig alloc] initWithSignalHandlerType: PLCrashReporterSignalHandlerTypeMach
                                                                        symbolicationStrategy: PLCrashReporterSymbolicationStrategyNone
                                                      shouldRegisterUncaughtExceptionHandler:YES];
    PLCrashReporter *reporter = [[PLCrashReporter alloc] initWithConfiguration: config];
    /* Save any existing crash report. */
    save_crash_report(reporter);
### **Details**

1. Which SDK version are you using?  1.10.0
3. Which OS version did you experience the issue on?  14.5
4. Which CocoaPods/Carthage/Xcode version are you using? cocoaPods : 1.11.2 Xcode 13
5. What device version did you see this error on? Were you using an emulator or a physical device? iPhone 12
6. What language are you using?e Cbjective C     Objective C
  
7. What third party libraries are you using?
bugly

**Comment by DmitriyKirakosyan** [comment]
Hi @alotofleo2 , thank you for reaching out to us!

Note, that PLCrashReporter may not work as expected when using along with another bug reporting SDK, in your case Bugly.
Can you try to reproduce the issue on an empty project without Bugly?

**Comment by DmitriyKirakosyan** [comment]
We haven't heard from you for a while so I'm closing this issue. Please let me know if the problem still reminds for you.
