### ISSUE TITLE
"The code signature version is no longer supported." (Carthage)

### ISSUE THREAD

**Issue by pepas-everly** [microsoft/plcrashreporter#231]
### **Description**

PLCrashReporter builds but fails to install on a physical device when using Carthage.

<img width="624" alt="Screen Shot 2022-04-01 at 12 33 21 PM" src="https://user-images.githubusercontent.com/99997577/161315301-191dbb59-f207-4474-a1da-16c5238312ef.png">

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Install Carthage: `brew install carthage`
2. Create a Cartfile: `echo 'github "microsoft/plcrashreporter" == 1.10.1' > Cartfile`
3. Build the framework: `carthage update --use-xcframeworks --platform iOS`
4. Drag Carthage/Build/CrashReporter.xcframework into the "Frameworks, Libraries and Embedded Content" section of the "General" tab of your target.
5. Build and run to a physical device.

The build will succeed, but will fail to install.  If you click "details" on the error popup, you'll see:

_"The code signature version is no longer supported."_

As a comparison, you can try the above steps with another framework, e.g. Kingfisher (`echo 'github "onevcat/Kingfisher" == 7.2.0' > Cartfile`) and it works just fine, so it appears the problem is specific to PLCrashReporter.

Note: my iOS project has "Push Notifications" added under "Signing and Capabilities".

### **Details**

1. Which SDK version are you using?  1.10.1
2. Which OS version did you experience the issue on?  Monterey 12.3
7. Which CocoaPods/Carthage/Xcode version are you using?  Carthage 0.38.0, Xcode 13.3
8. What device version did you see this error on? Were you using an emulator or a physical device?  Physical device, running iOS 15.3.1
9. What language are you using?
    - [ ] Objective C
    - [ X ] Swift
10. What third party libraries are you using?  Just PLCrashReporter

**Comment by pepas-everly** [comment]
Update: it appears the issue is that the framework needs to be changed "Embed and sign" to "Do not embed" after dragging it into the project.

**Comment by pepas-everly** [comment]
If someone else can independently confirm this issue and the fix, then the action item from this issue can be to update the Carthage instructions in the README.

**Comment by MatkovIvan** [comment]
Hi @pepas-everly,

Thanks for getting in touch!
It's expected behaviour because it builds as "static" library that should not be embedded.

> can be to update the Carthage instructions in the README.

Actually README already contains this info (but not in Carthage sections, yep).

> NOTE: PLCrashReporter xcframework contains static binaries for iOS and tvOS, and dynamic binaries for macOS. When adding the framework to your project make sure that in Frameworks, Libraries and Embedded Content section Embed is selected to Do not embed for iOS and tvOS and Embed and Sign for macOS. PLCrashReporter-Static-{version}.zip is an exception - it contains static frameworks for all platforms.

We'll think about how to improve the docs.

Best,
Ivan
