### ISSUE TITLE
Consider adding `symbolicatecrash` to the tools

### ISSUE THREAD

**Issue by Cyberbeni** [microsoft/plcrashreporter#233]
From Xcode 13.3 release notes:

> The symbolicatecrash script is deprecated. Instead, use the atos command-line tool. For more information about this tool, see [Adding Identifiable Symbol Names to a Crash Report](https://developer.apple.com/documentation/Xcode/adding-identifiable-symbol-names-to-a-crash-report). (82929755)

When used from inside Xcode 13.3, it also prints a warning that it will be removed from a future release.

I think it would be a good idea to include that script in PLCrashReporter releases, or even improve the script. (Currently it can only symbolicate files one by one but atos' runtime doesn't depend much on the number of arguments, so collecting lines to symbolicate from multiple files would speed up the process -- this can be done by normalizing the addresses to a load address of 0x10 based on my testing)

**Comment by DmitriyKirakosyan** [comment]
Hi @Cyberbeni , thank you for reaching out to us!

The `symbolicatecrash` util is not a part of the `PLCrashReporter` library. it is only mentioned in `README.md` as a suggestion on how to symbolicate an apple crash report.

Anyway thank you for letting us know, we will update the Readme file.

**Comment by DmitriyKirakosyan** [comment]
The PR updating README is merged. Closing.
