### ISSUE TITLE
PLCrashReporterConfig is always setting shouldRegisterUncaughtExceptionHandler to YES in ctor

### ISSUE THREAD

**Issue by mongosr2** [microsoft/plcrashreporter#236]
### **Description**

For the following initializer, shouldRegisterUncaughtExceptionHandler is always set to YES rather than taking the value passed to the constructor.  I have added what I believe it should be changed to below it.

/**
 * Initialize a new PLCrashReporterConfig instance.
 *
 * @param signalHandlerType The requested signal handler type.
 * @param symbolicationStrategy A local symbolication strategy.
 * @param shouldRegisterUncaughtExceptionHandler Flag indicating if an uncaught exception handler should be set.
 */
- (instancetype) initWithSignalHandlerType: (PLCrashReporterSignalHandlerType) signalHandlerType
                     symbolicationStrategy: (PLCrashReporterSymbolicationStrategy) symbolicationStrategy
    shouldRegisterUncaughtExceptionHandler: (BOOL) shouldRegisterUncaughtExceptionHandler
{
  return [self initWithSignalHandlerType: signalHandlerType symbolicationStrategy: symbolicationStrategy shouldRegisterUncaughtExceptionHandler: YES basePath: nil];
}

Shouldn't this be changed to

/**
 * Initialize a new PLCrashReporterConfig instance.
 *
 * @param signalHandlerType The requested signal handler type.
 * @param symbolicationStrategy A local symbolication strategy.
 * @param shouldRegisterUncaughtExceptionHandler Flag indicating if an uncaught exception handler should be set.
 */
- (instancetype) initWithSignalHandlerType: (PLCrashReporterSignalHandlerType) signalHandlerType
                     symbolicationStrategy: (PLCrashReporterSymbolicationStrategy) symbolicationStrategy
    shouldRegisterUncaughtExceptionHandler: (BOOL) shouldRegisterUncaughtExceptionHandler
{
  return [self initWithSignalHandlerType: signalHandlerType symbolicationStrategy: symbolicationStrategy shouldRegisterUncaughtExceptionHandler: shouldRegisterUncaughtExceptionHandler basePath: nil];
}
### **Repro Steps**

Please list the steps used to reproduce your issue.

1.
2.

### **Details**

1. Which SDK version are you using? this is in 10, 10.1, and master.  I haven't looked at others
2. Which OS version did you experience the issue on? 15
3. Which CocoaPods/Carthage/Xcode version are you using?13.2
4. What device version did you see this error on? Were you using an emulator or a physical device? Physical Device
5. What language are you using? Xamarin and ObjC
    - [ X] Objective 
    - [ ] Swift
6. What third party libraries are you using? None

**Comment by busec0** [comment]
:facepalm:

**Comment by DmitriyKirakosyan** [comment]
Hi @mongosr2 , thank you for catching that! I'll prepare a PR.

**Comment by MatkovIvan** [comment]
Fixed in the latest release
