### ISSUE TITLE
ios  catalyst  Unable to collect crash 

### ISSUE THREAD

**Issue by hardy720** [microsoft/plcrashreporter#246]
My project supports IOS catalyst. In MAC, after a crash, I can't get the crash information. What's the answer?

**Comment by AnatolyPristensky** [comment]
Hello @hardy720, could you please share more detailed information about your issue?
Also, please make sure that you doesn't use debug mode.

**Comment by hardy720** [comment]
Thank you!      
I want to collect the collapse information of our app through plcrashreporter, which works well in IOS

Because our app supports catalyst, it can run on the Mac, but after the plcrashreporter crashes in the Mac, start the app, and it cannot detect the crash information

I tested it under release, and it couldn't get the crash information. What's the matter? The framework I imported contains ios-arm64_ x86_ 64-macc
![截屏2022-07-18 16 48 46](https://user-images.githubusercontent.com/92299732/179478189-7d3d23ee-63db-4d94-975b-075c0380143c.png)
atalyst

**Comment by AnatolyPristensky** [comment]
@hardy720, could you please uncheck "Debug executable" checkbox and try again?

<img width="129" alt="Screenshot 2022-07-18 at 12 10 18" src="https://user-images.githubusercontent.com/84129877/179490317-214f9503-a561-4c6d-8a3d-96fae5bb228c.png">

**Comment by hardy720** [comment]
@AnatolyPristensky  thank you . We can get crash information normally,.
