### ISSUE TITLE
 Can you let the app not exit the app after an error occurs? I want to prompt the user, and then the user will exit the app after confirming 

### ISSUE THREAD

**Issue by hardy720** [microsoft/plcrashreporter#247]
Now, when an error occurs in the app, it will exit the app directly This experience is not good,

I want to tell users through the pop-up box that the app is going to collapse after an error occurs.     When the user clicks OK, the app exits

I can implement it with runloop, but my implementation fails after using plcrashreporter. Does plcrashreporter have such a function?

**Comment by DmitriyKirakosyan** [comment]
Hi @hardy720 ,

PLCRashReporter is a tool for collecting crashes and preparing reports. The crash data is collected in a non-returnable state when crash is already happened and thus it will only be available on the next app launch.

As for the callback, it does provide [setCrashCallbacks](https://github.com/microsoft/plcrashreporter/blob/master/Source/PLCrashReporter.h#L143) API for setting a callback right after the crash is happened and saved, however the range of actions you can perform in this callback is limited as the application is already in half-termination state. Eg. you will not able to show any UI in this callback. The callback is mainly for the clean-up purpose.

Closing this issue, but feel free to reopen if you have additional questions or concerns.
