### ISSUE TITLE
found a crash  in version 1.10.1 [Mac Application]

### ISSUE THREAD

**Issue by iceluo** [microsoft/plcrashreporter#256]
I use CrashReporter in the Mac app. The current version is 1.10.1.
I collected some crashes below

Thread 0 Crashed:
0   libsystem_kernel.dylib              0x00007fff69eba33a 0x7fff69eb3000 + 29498
1   libsystem_c.dylib                   0x00007fff69e41808 0x7fff69dc2000 + 522248
2   CrashReporter                       0x000000011333a0f9 -[PLCrashReporter setCrashCallbacks:].cold.1 + 147705 (PLCrashReporter.m:0)
3   CrashReporter                       0x000000011331dbed -[PLCrashReporter generateLiveReportWithThread:] + 31725 (PLCrashReporter.m:663)
4   HIToolbox                           0x00007fff2e9d8bba 0x7fff2e9d0000 + 35770
5   HIToolbox

**Comment by AnatolyPristensky** [comment]
Hello @iceluo, 
Could you please provide more details?
Please list the steps used to reproduce your issue.

**Comment by AlexeyBudynkov** [comment]
@iceluo At this moment I'm closing this ticket. Feel free to reopen it again if you will have this problem again
