### ISSUE TITLE
Can I integrate PLCrashReporter within a framework? 

### ISSUE THREAD

**Issue by mnive93** [microsoft/plcrashreporter#273]
### **Description**
I want to enable crash reporting inside a framework. Can I use PLCrashReporter within that framework? If the parent app is already using a crash reporting system and when they integrate our framework will it cause any issues?

### **Details**

1. Which SDK version are you using? 1.11.0
2. Which OS version did you experience the issue on?
3. Which CocoaPods/Carthage/Xcode version are you using?
4. What device version did you see this error on? Were you using an emulator or a physical device?
5. What language are you using?
    - [x] Swift
6. What third party libraries are you using?

**Comment by DmitriyKirakosyan** [comment]
Hi @mnive93 , thank you for reaching out!
Using PLCrashReporter along with another crash reporting tool is not supported and can lead to partially or fully disabling one or another crash reporter. So if you integrate PLCR in your framework and your framework's client is already using another crash reporter tool, it may cause issues.

I hope I answered your question, but feel free to ask any additional questions.

**Comment by mnive93** [comment]
@DmitriyKirakosyan Is there any way for a third party to track the performance and metrics of a library to provide insights like crash-free percentage and other key metrics?

**Comment by DordeDimitrijev** [comment]
Hello @mnive93,
PLCrashReporter doesn't have a method defined for stopping listening for crashes. On the other hand it can be done manually by unregistering signal handlers and cleaning up the context, but enabling afterwards could be complex since you'd need to setup the signal handlers again.
