### ISSUE TITLE
Xcode 14.3 beta support

### ISSUE THREAD

**Issue by AvdLee** [microsoft/plcrashreporter#276]
### **Description**

The following compiler error appeared: 
![CleanShot 2023-03-08 at 11 34 36@2x](https://user-images.githubusercontent.com/4329185/223690516-192e23be-069e-443b-938f-9e416cc40442.jpg)

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Download Xcode 14.3 beta (1 or 2)
2. Compile

**Comment by DmitriyKirakosyan** [comment]
Hi @AvdLee , thank you for reporting this issue!
`PTHREAD_MUTEX_INITIALIZER` is part of `pthread.h`, and I can't find any information of changed/deprecated `pthread` in xcode 14.3 beta. Can it be a bug of beta?

I'll try to install the xcode 14.3 beta 2 and reproduce it on my end.

**Comment by DmitriyKirakosyan** [comment]
Meanwhile, I recommend you to install a copy of Xcode 14.2. It will unblock you until we or apple resolve this issue.

**Comment by DmitriyKirakosyan** [comment]
Hi @AvdLee , are you still facing this issue on Xcode 14.3?

**Comment by AvdLee** [comment]
@DmitriyKirakosyan it looks like it's all good now! Closing the issue 🙂
