### ISSUE TITLE
Warnings when building client code with `CLANG_WARN_OBJC_INTERFACE_IVARS=YES`

### ISSUE THREAD

**Issue by siegel** [microsoft/plcrashreporter#278]
### **Description**

When building my PLCrashReporter framework client with `CLANG_WARN_OBJC_INTERFACE_IVARS=YES` (corresponding to the "Interface Declarations of Instance Variables" GUI build setting in the "Apple Clang - Warnings - Objective-C" section), a total of 73 warnings are generated, corresponding to ivars declared in PLCrashReporter implementation classes.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Open a simple project which links against the PLCrashReporter framework (macOS).
2. `#include <CrashReporter/CrashReporter.h>`
3. Make sure `CLANG_WARN_OBJC_INTERFACE_IVARS` is set to `YES`.
4. Compile.

### **Details**

1. SDK version 1.11.0
2. macOS 13.3.1
3. Xcode version 14.3
4. using Objective-C

**Comment by siegel** [comment]
These warnings are also reproducible as errors when building the framework itself from source with this option turned on.

**Comment by DmitriyKirakosyan** [comment]
Fixed.
