### ISSUE TITLE
Xcode 15 build error

### ISSUE THREAD

**Issue by abdulalim** [microsoft/plcrashreporter#284]
### **Description**

While trying build in Xcode 15 beta, the library gives this build error: 

Null objc class data for '_OBJC_METACLASS_$_PLCrashHostInfo' in '/Users/username/Library/Developer/Xcode/DerivedData/Appname-fcjusjfuhxkoaxgadychxkraboie/Build/Products/Debug-iphoneos/CrashReporter.o'

### **Repro Steps**

1. Install XCode 15 beta
2. Try building the project

### **Details**

1. Which SDK version are you using? Version 4.x.x or 5.x.x
2. Which OS version did you experience the issue on? iOS 16, iOS 17
3. Which CocoaPods/Carthage/Xcode version are you using? it's Swift Package Manager
4. What device version did you see this error on? Were you using an emulator or a physical device? Real devices and simulators all iPhones
5. What language are you using?
    - [ X] Objective C
    - [ X] Swift
6. What third party libraries are you using? App center

**Comment by AvdLee** [comment]
I've been experiencing the same!

**Comment by AvdLee** [comment]
Alright, so this seems to be related to a new linker introduced in beta 3 of Xcode 15.0. For now, we can solve this by adding `-ld64` to the 'Other Linker Flags' build setting. However, it would be great if the new linker supported building this project.

Related: https://github.com/firebase/firebase-ios-sdk/issues/11516

**Comment by futuretap** [comment]
Seeing the same issue. Filed FB12592304 (ld-prime linker error when building PLCrashReporter).

**Comment by abdulalim** [comment]
> Alright, so this seems to be related to a new linker introduced in beta 3 of Xcode 15.0. For now, we can solve this by adding `-ld64` to the 'Other Linker Flags' build setting. However, it would be great if the new linker supported building this project.
> 
> Related: [firebase/firebase-ios-sdk#11516](https://github.com/firebase/firebase-ios-sdk/issues/11516)

Thanks, yes looks this works. But hope it will be fixed soon

**Comment by MikhailSuendukov** [comment]
Thank you for contacting us. Apparently this error is in the new version of the linker, so I think that we will wait for this fix in the next versions of XCode.
