### ISSUE TITLE
App getting crashed on launch.

### ISSUE THREAD

**Issue by abubakar-9013** [microsoft/plcrashreporter#286]
### **Description**
I am using CrashReporter.framework in my test project. I initialise it using the code provided in the documentation. I am successfully getting the crash report whenever there is a  crash, but there is that one crash report that I am always getting. It is not my app crash report but I am getting it whenever there isn't any pending crash of my app. 

**Steps to Reporduce**
- Integrate CrashReporter.framework by dragging and dropping into the project
- Initialise it like mentioned in the documentation.
- Run the project without having any crash in pending.
- A crash report will appear.
- Produce a crash in your app.
- Close and open app again, then in logs you will see your app's crash report.
- Close and open app again, you'll get the first crash report again that isn't of your app.

<img width="1464" alt="Screenshot 2023-08-28 at 10 47 00 AM" src="https://github.com/microsoft/plcrashreporter/assets/69431968/9b77943c-9bce-4e78-81e0-4c4c5736dcde">

I am trying `crashReporter.purgePendingCrashReport()` but it isnt working. My question is why it is happening and if it is somehow  the default behaviour, how come i'll be able to identify if there are some crashes pending on my side of app.

**Comment by DmitriyKirakosyan** [comment]
Hi @abubakar-9013 , thank you for reaching out!

This crash indicates that the system is killing your app, probably due to unexpectedly long work on main thread.
Does your app work well when you run it normally, without triggering a crash? Does it respond to buttons etc?

If it works well, then I expect it to be a bug of new iOS or Xcode. Can you share more info on your app and your tooling? What is your Xcode version?
Is it possible for you to share a demo app with us so we can reproduce it on our end?

**Comment by abubakar-9013** [comment]
Okay, so I am getting a strange issue that I havent noted before. I was just implementing CrashReporter on a test project which didn't included any UI. Just simple plain view controller in which i was producing crash on touches began function. But now, when i have added some UI elements in it, then whenever i launch my project while attaching my device, via xcode, it crashes.  And when i launch my app directly from device, and not from xcode, it runs fine.

Following are my details
Xcode: 14.3.1
Device: iPhone 13
Device OS: 16.0
You can clone my test project : https://github.com/abubakar-9013/PL

**Comment by abubakar-9013** [comment]
Also, when initializing `PLCrashReporterConfig`, if i use .BSD as `signalHandlerType`, then app doesn't crash but it doesnt capture crash either like fatal crash as i get `false` in `hasPendingCrashReport`

**Comment by abubakar-9013** [comment]
I am guessing this might be the issue: 

`The Mach exception handler executes in-process, and will interfere with debuggers when they attempt to
     * suspend all active threads (which will include the Mach exception handler). Mach-based handling
     * should not be used when a debugger is attached.`

**Comment by abubakar-9013** [comment]
Closing this thread as it was not Library issue.
