### ISSUE TITLE
README Contributing section still refers to the old repo

### ISSUE THREAD

**Issue by yousefhamza** [microsoft/plcrashreporter#29]
The contributing [section](https://github.com/microsoft/plcrashreporter#contributing) still refers to the old repo:

> git clone --recursive https://github.com/microsoft/PLCrashReporter-Fork.git

Is this intentional or it should be updated?

**Comment by MatkovIvan** [comment]
Hi @yousefhamza ,

Yeah, it's probably because of bad merge. Thanks for reporting, we'll fix it

**Comment by yousefhamza** [comment]
@MatkovIvan Thanks 🙏
