### ISSUE TITLE
Kotlin multi-platform exception handling issue 

### ISSUE THREAD

**Issue by alilyinooma** [microsoft/plcrashreporter#293]
### **Description**

See the https://github.com/microsoft/appcenter-sdk-apple/issues/2519

This is an iOS specific problem, Android version works fine based on original MSAppcener bug report. I personally did not try Android app yet. 

### **Repro Steps**

The iOS app hangs trying to handle the Kotlin multi-platform exception using MSAppCenter (based on [plcrashreporter](https://github.com/microsoft/plcrashreporter))

![Screenshot 2023-12-14 at 12 12 44 PM](https://github.com/microsoft/plcrashreporter/assets/111453493/5fc73e63-8997-4c14-b51b-93ce4ef7b7d9)

### **Details**

1. Which SDK version are you using? - 1.11.1
2. Which OS version did you experience the issue on? - iOS 17.2
3. Which CocoaPods/Carthage/Xcode version are you using? - xCode 15.1
4. What device version did you see this error on? Were you using an emulator or a physical device? - physical iPhone 15 Pro Plus
5. What language are you using?
    - [x] Swift
6. What third party libraries are you using?
    - [x] Kotlin multi-platform
    - [x] MSAppCenter

**Comment by alilyinooma** [comment]
I can provide a test project if needed

**Comment by MikhailSuendukov** [comment]
Hi @alilyinooma and sorry for the long delay. Yes, it would be great if you provided us with a small demo application on which we can reproduce this error.

**Comment by ahmadashraf604** [comment]
Hi @MikhailSuendukov we have the same issue, Any updates about the fix 🙏 
if you still need the demo app, you can use [this](https://github.com/ahmadashraf604/PLCrashReporterHangDemo)

**Comment by ahmadashraf604** [comment]
Hi @MikhailSuendukov @DmitriyKirakosyan Any Updates or ETA to fix this issue 🙏
Also, we found this issue does not happen if we used the debug build of PLCrashReporter, I don't know if this info will help you or not

**Comment by MikhailSuendukov** [comment]
We are prioritizing other bug fixes which affects more customers so there is no ETA for fix. Of course we warmly welcome any contributions.

**Comment by 0xnm** [comment]
We are experiencing the same issue with the Kotlin 2.0.0 and PLCrashReporter 1.11.2.

**Comment by 0xnm** [comment]
There is nothing to do from PLCrashReporter side as it is mentioned in https://github.com/microsoft/plcrashreporter/issues/320#issuecomment-2459162545. Just Kotlin 2.0.20-Beta1 or above is needed to make it work.
