### ISSUE TITLE
Apple Privacy Manifest 

### ISSUE THREAD

**Issue by wenfeng-duan** [microsoft/plcrashreporter#294]
Hi team,
Is there a plan to include the PrivacyInfo.xcprivacy manifest as required by Apple?
ref: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

Thanks,
Duan

**Comment by WWSellers** [comment]
Also called a "privacy manifest".  This was covered in WWDC 2023 session 10060, titled "Get started with Privacy Manifests"
https://developer.apple.com/videos/play/wwdc2023/10060/

Apple published its list of "privacy-impacting SDKs" at the link below. This list includes Google Protobuf. Any SDK included in the list is required to provide a privacy manifest and signature.
https://developer.apple.com/support/third-party-SDK-requirements/

Apple has stated that manifests will be required for apps and embedded SDKs starting in "Spring 2024".

**Comment by MikhailSuendukov** [comment]
Thank you for contacting us, we will start working on this.

**Comment by tamwei** [comment]
I saw that the PR for this issue has been merged. Will a new version be released in the near future?

**Comment by AnatolyPristensky** [comment]
@tamwei, we are planning to make a new release soon. I'll update this issue once release will be available.

**Comment by rahulrkp** [comment]
Is there a planned release date for the update that includes the "privacy manifest"?

**Comment by WWSellers** [comment]
Apple has announced the updated schedule for warnings and rejections here: https://developer.apple.com/news/?id=3d8a9yyh
**March 13**:  begin sending email warnings 
**May 1**: possible app rejections begin

**Comment by ilanahaddad** [comment]
hi, i would also like to know if there's a release planned soon to include the privacy manifest that is currently in main. It would be greatly appreciated. thanks!

**Comment by trevor-holliday-instacart** [comment]
It looks like there is PR open for the manifest. Does that mean a new release should be coming soon?

**Comment by zeshaanAli94** [comment]
Hi, I see the preparation for release v1.11.2. I was wondering what is the current planned release date for this update?

**Comment by drmichal** [comment]
Hello! Any progress on this issue? :)

**Comment by skyfoxa** [comment]
@MikhailSuendukov I see there is a new package version, the [release notes](https://github.com/microsoft/plcrashreporter/releases/tag/1.11.2) say it contains the privacy manifest. Does it mean this issue can be closed?
