### ISSUE TITLE
When dealing with Kotlin Multiplatform (KMP) and encountering a hang instead of crash on iOS.

### ISSUE THREAD

**Issue by ManoharaReddyP** [microsoft/plcrashreporter#320]
### **Description**

App using plcrashreportergets version 1.11.2 gets Hang instead of crashing when using with Kotlin multi-platform. 

Could you please suggest is there way to fix this issue? any workaround solution available?

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create sample app using KPM
2. crash sample crash like index out of bound exception and see app is getting Hang instead of crash.

### **Details**

1. Which SDK version are you using? -> 1.11.2
2. Which OS version did you experience the issue on? -> 17.4
3. Which CocoaPods/Carthage/Xcode version are you using? -> Xcode 15.2, CocoaPods 1.13.0
4. What device version did you see this error on? Were you using an emulator or a physical device? Simulator 
5. What language are you using?
    Framework is written in Objective C which uses PLCrashreporter
6. What third party libraries are you using?
None

**Comment by IlyaBausovAkvelon** [comment]
Hi @ManoharaReddyP
Thank you for reporting this issue. Unfortunately PLCrashReporter currently does not have support for Kotlin Multiplatform and we are not planning to add it in the near future.
I will close this issue.

**Comment by 0xnm** [comment]
`PLCrashReporter` is working fine with Kotlin Multiplatform, Kotlin version `2.0.20-Beta1` or above should be used to make it work.

**Comment by ManoharaReddyP** [comment]
@0xnm All the versions are supported or it will support any specific PLCrashreporter version onwards?
