### ISSUE TITLE
fatal signals not caught

### ISSUE THREAD

**Issue by cynicer** [microsoft/plcrashreporter#326]
### **Description**
PLCrashReporter doesn't create crash reports when a fatal signal like SIGSEGV occurs. Not sure if this is a problem of testing, but for example with KSCrash this seems to be working.

### **Repro Steps**
1. Start the sample project ([UndetectedSignal.zip](https://github.com/user-attachments/files/17542220/UndetectedSignal.zip)
) on simulator or device
2. Press "Press me!" button
2. App crashed
3. No stack trace is printed on next start (see PLCrashIntegration.swift#L53)

### **Details**
1. Which SDK version are you using?
1.11.2
2. Which OS version did you experience the issue on?
18.0.1
3. Which CocoaPods/Carthage/Xcode version are you using?
Xcode 15.3
4. What device version did you see this error on? Were you using an emulator or a physical device?
iPad Air 4th gen and Simulator (17.4, 18.0)
5. What language are you using?
    - [ ] Objective C
    - [x] Swift
6. What third party libraries are you using?
None, see sample project.

**Comment by DordeDimitrijev** [comment]
Hello @cynicer if you'd like to get report based on SIGSEGV signal you'd need to configure plcrashreporter with signalHandlerType as in the snippet bellow. Let me know if this works out for you.
` let config = PLCrashReporterConfig(signalHandlerType: .BSD, symbolicationStrategy: .all)`

**Comment by DordeDimitrijev** [comment]
>   As such, while Mach exceptions may catch some cases that BSD signals can not, they are not a perfect solution,
>   and may also provide less insight into the actual failures that occur. By comparison, the BSD signal interface
>   is both fully defined and architecture independent, with any necessary interpretation of the Mach exception
>   codes handled in-kernel at the time of exception dispatch. It is generally recommended by Apple as the preferred
>   interface, and should generally be preferred by PLCrashReporter API clients.

You can read it in depth more [here](https://github.com/microsoft/plcrashreporter/blob/2e8dc9e58f49153d41310a1519bf57a86bc168ab/Source/CrashReporter.h#L242)
In summary there are signals that the mach signalhandler can't  catch so BSD is used instead.

**Comment by cynicer** [comment]
Yes, I'm aware of that. I'm just wondering if there's a specific reason that there is no option to combine the two interfaces and listen for Mach exceptions and BSD signals? Since the Mach handling is based on the SIGABRT already.

Otherwise it answers my initial question/problem, thanks!

**Comment by DordeDimitrijev** [comment]
Signal code like SIGSEGV is out or process signal so as you can see [here](https://github.com/microsoft/appcenter-sdk-apple/blob/a312728bb7d7e15e9f2f38f08608c3be44118550/Vendor/iOS/PLCrashReporter/include/CrashReporter.h#L241) it is mentioned that mach handler handles only in process issues. You'd need to use in your scenario BSD to catch signals that are out of process signals but by default mach is proposed as default one since the use of the library is to generate crash reports for in-process issues.
