### ISSUE TITLE
the app crashes on startup

### ISSUE THREAD

**Issue by MuYanQin** [microsoft/plcrashreporter#333]
### **Description**

Create a new MacApp project, use SPM to add version 1.11.2 of PLCrashReporter, and the app crashes on startup.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create a new MacApp project  use SPM to add version 1.11.2 of PLCrashReporter

2.the app crashes on startup.

### **Details**

1. Which SDK version are you using? -> 1.11.2
2. Which OS version did you experience the issue on? -> macos 15.1
3. Which CocoaPods/Carthage/Xcode version are you using? -> xcode 16.2
4. What device version did you see this error on? Were you using an emulator or a physical device? -> xcode run to my mac. macos 15.1
5. What language are you using?
    - [ ] Objective C
    - [ ✅] Swift
6. What third party libraries are you using? -> none
7. ![Image](https://github.com/user-attachments/assets/c8348a2c-daaf-4338-9923-63c43a504b82)
8.my test project :https://github.com/MuYanQin/test.git

**Comment by mkardas98** [comment]
In the README you have information:

```
import CrashReporter

...
// Uncomment and implement isDebuggerAttached to safely run this code with a debugger.
// See: https://github.com/microsoft/plcrashreporter/blob/2dd862ce049e6f43feb355308dfc710f3af54c4d/Source/Crash%20Demo/main.m#L96
// if (!isDebuggerAttached()) {

  // It is strongly recommended that local symbolication only be enabled for non-release builds.
  // Use [] for release versions.
  let config = PLCrashReporterConfig(signalHandlerType: .mach, symbolicationStrategy: .all)
  guard let crashReporter = PLCrashReporter(configuration: config) else {
    print("Could not create an instance of PLCrashReporter")
    return
  }

  // Enable the Crash Reporter.
  do {
    try crashReporter.enableAndReturnError()
  } catch let error {
    print("Warning: Could not enable crash reporter: \(error)")
  }
// }
```

CrashReport will not work alongside the Xcode debugger.

**Comment by MuYanQin** [comment]
#if !TARGET_OS_IPHONE
    return false;
#endif

I saw that this check is only done for iPhone, so I assumed that macOS doesn't need this condition.
