### ISSUE TITLE
Query about the road map

### ISSUE THREAD

**Issue by jessejiang0214** [microsoft/plcrashreporter#334]
Hi there, 

As we know AppCenter will be retire, so we trying to find the replace solution, we are thinking about implement it by our-selves. We need to use this project and we want to know how long Microsoft will maintain this project?

Thanks
Jesse

**Comment by MikhailSuendukov** [comment]
Hello, and thank you for reaching out to us. After retirement of AppCenter the PLCrashreporter repository will be archived. However, you are welcome to fork the repository to continue working on it and maintaining it independently.
