### ISSUE TITLE
1.4 doesn't demangle function names in Objective C++ sources

### ISSUE THREAD

**Issue by sevaa** [microsoft/plcrashreporter#45]
Repro: rename a source file to .mm. Make a device build, run on a device without a debugger.

Have it crash in a standalone (i. e. not a class method) function. Observe the mangled function name in the call stack in the crash report.

**Comment by MatkovIvan** [comment]
Hi @sevaa,
Thanks for getting in touch!
Could you please clarify a few things to help understand the case better:
1. How do you get that crash report? What flags are used to initialize the SDK? I assume it's runtime symbolycation feature, just making sure.
2. Why 1.4 is mentioned explicitly? Is it regression or feature request? For now I see this as a new feature request.

**Comment by sevaa** [comment]
I'm using QuincyKit, antiquated as it is. Don't set any of the PLCrashReporter settings manually. Until now, I was on PLCrashReporter 1.2, and it didn't try to symbolicate on the device (that I know of). Symbolication was happening on the server, C++ names properly detangled.

In terms of PLCrashReporter parameters, here's all I found in QuincyKit:

```
      PLCrashReporterSignalHandlerType signalHandlerType = PLCrashReporterSignalHandlerTypeBSD;
      if (self.isMachExceptionHandlerEnabled) {
        signalHandlerType = PLCrashReporterSignalHandlerTypeMach;
      }
      PLCrashReporterConfig *config = [[PLCrashReporterConfig alloc] initWithSignalHandlerType: signalHandlerType
                                                                         symbolicationStrategy: PLCrashReporterSymbolicationStrategyAll];
      _plCrashReporter = [[PLCrashReporter alloc] initWithConfiguration: config];
```

**Comment by MatkovIvan** [comment]
`PLCrashReporterSymbolicationStrategyAll` means that the library will try to perform local symbolication via all available strategies.
1.4 fixes some bugs in run-time symbolication, so I guess that's why it can find function names that were missed before.

You can use `PLCrashReporterSymbolicationStrategyNone` option to perform symbolication on the server.

Demangling C++ function names wasn't performed by this library.

**Comment by sevaa** [comment]
Well, then consider this a feature request.

**Comment by ahdbilal** [comment]
Thanks. It has been added to feature backlog. I will post an update if we move forward with it.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
