### ISSUE TITLE
Cocoapods - certificate doesn't match the target host name

### ISSUE THREAD

**Issue by ngsison** [microsoft/plcrashreporter#46]
The image below is the result I got after running `pod install`

![image](https://user-images.githubusercontent.com/20357514/71871943-da241380-3155-11ea-8e28-f0aa408370d0.png)

**Comment by jaelim-ms** [comment]
In this repository we only support 1.4.0 which is available in [release](https://github.com/microsoft/plcrashreporter/releases/tag/1.4.0). Sorry to say it but Cocoapods integration isn't supported, you have to manually add the binary to your project.

**Comment by MatkovIvan** [comment]
From description of [this cocoa pod](https://cocoapods.org/pods/PLCrashReporter):

> This subtree contains user-contributed code that is not part of the core PLCrashReporter distribution. This software is not provided by or maintained by Plausible Labs, and no support is provided.

As @jaelim-ms already said, cocoapods is not officially supported and we are not the maintainers of this pod.

**Comment by ramil-k** [comment]
But still, the website has an ssl issue, where it should be reported?

**Comment by annakocheshkova** [comment]
Hey, we are not the maintainers of this website unfortunately.

**Comment by lumaxis** [comment]
@ramil-k We're working on getting the domain transferred and will simply redirect it to this GitHub repo. Just a few formalities to figure out.

**Comment by MatkovIvan** [comment]
Hi there, we've fixed the urls in the pod, so it should work now.

**Comment by ngsison** [comment]
> Hi there, we've fixed the urls in the pod, so it should work now.

Verified working. Thank you!
