### ISSUE TITLE
Why doesn't PLCrashReporter recognize a crash with code - 0x8badf00d 

### ISSUE THREAD

**Issue by shradda02** [microsoft/plcrashreporter#47]
I have PLCrashReporter integrated into my app and I have some crashes reported because of the watch dog timeout. But PLCrashReporter does not seem to recognize this as a crash and I dont see a report being generated for this.

Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: Namespace SPRINGBOARD, Code 0x8badf00d
Termination Description: SPRINGBOARD, process-exit watchdog transgression: application<>:38090 exhausted real (wall clock) time allowance of 5.00 seconds | ProcessVisibility: Background | ProcessState: Running | WatchdogEvent: process-exit | WatchdogVisibility: Background | WatchdogCPUStatistics: ( | "Elapsed total CPU time (seconds): 2.570 (user 2.570, system 0.000), 9% CPU", | "Elapsed applicatn CPU time (seconds): 0.124, 0% CPU" | )
Triggered by Thread:  0

**Comment by WWSellers** [comment]
If I recall correctly, an app does not receive a SIGKILL signal. The app is just killed by the OS from the outside.

Since PLCrashReporter must work within the process of the app to generate reports, it gets no opportunity to do its work.

**Comment by annakocheshkova** [comment]
Unfortunately, out-of-process issues can not be handled on iOS; it requires that a Mach exception handler operate out-of-process, which is impossible on iOS.
For more information, refer to [in-code documentation](https://github.com/microsoft/appcenter-sdk-apple/blob/a312728bb7d7e15e9f2f38f08608c3be44118550/Vendor/iOS/PLCrashReporter/include/CrashReporter.h#L241).

**Comment by annakocheshkova** [comment]
I'm closing the issue, feel free to re-open if you have any more questions.
