### ISSUE TITLE
Unwinding fails in a swift classes on arm64e only 

### ISSUE THREAD

**Issue by yousefhamza** [microsoft/plcrashreporter#50]
I created a simple swift class to simulate a crash:
```
class SwiftViewController: UIViewController {

    @IBOutlet weak var myButton: UIButton!

    override func viewDidLoad() {
        super.viewDidLoad()
        print([1, 2, 3][4])
    }
}
```

I just noticed that this crash on arm64e devices have only the _first_ frame in each thread, except frames which have the app frames at the top it unwinds successfully through the apps' frames until the first non-app frame (iOS SDK frame) then fails to unwind again.

I dug a little deeper in the logs, it says that it could not find the loaded image for the current `pc `, however the images in which unwinding fails are loaded.

**Comment by MatkovIvan** [comment]
Hi @yousefhamza ,

Thanks for the report. I see these errors in the log, but the library is still able to generate full stacktrace for me (because of usage [this fallback](https://github.com/microsoft/plcrashreporter/blob/05d34741d3a90bbed51214983110943831ae5943/Source/PLCrashFrameWalker.c#L197)).
However, it's definitely a bug and I've already managed to narrow it down. It's because of [pointer authentication](https://developer.apple.com/documentation/security/preparing_your_app_to_work_with_pointer_authentication) that aren't handled well at the moment.

**Comment by yousefhamza** [comment]
In our case it seems that maybe one of optimizations applied removes the `frame pointer` which makes the fallback fails as well.

Thanks for looking into it and let me know If I can help.

**Comment by MatkovIvan** [comment]
@yoannchaudet I've made a PR with the fix - #51
It's still under review/testing, but feel free to check this out.
Let me know if it works for you. Also, feel free to leave review comments on this PR.

**Comment by yousefhamza** [comment]
@MatkovIvan Thanks for the quick fix 🙏 

That does seem like the required change BUT, I looked into Crashlytics codebase (since they became open source recently) and I found out that they stopped using `ptrauth_strip` and masked the bits themselves [here](https://github.com/firebase/firebase-ios-sdk/blob/master/Crashlytics/Crashlytics/Helpers/FIRCLSThreadState.c#L55).

**Comment by yousefhamza** [comment]
@MatkovIvan Thanks for the quick fix 🙏

That does seem like the required change, however when I looked into Crashlytics codebase (since they became open source recently) and I found out that they stopped using `ptrauth_strip` and masked the bits themselves here.

**Comment by MatkovIvan** [comment]
Hm, yeah, I see the comment [there](https://github.com/firebase/firebase-ios-sdk/blob/3dc11858ff5bfc8e40bde33dd3fe16b04d215a9a/Crashlytics/Crashlytics/Helpers/FIRCLSThreadState.c#L51-L55):
```c
// We found later that ptrauth_strip doesn't seem to do anything. In many cases, the upper bits were
// already stripped, so for most non-system-library code, Crashlytics would still symbolicate. But
// for system libraries, the upper bits were being left in even when we called ptrauth_strip.
// Instead, we're bit masking and only allowing the latter 36 bits.
```

However, it works during testing for me. _Probably_, they tried to use another second parameter. When I experimented with it, it really can leave it as is with the value that sounds applicable there. But it works with the usage of the correct one.

**Comment by yousefhamza** [comment]
Sounds good 👍
